### ISSUE TITLE
O2 generator is unreliable

### ISSUE THREAD

**Issue by DarkwarriorJ** [zmaster587/AdvancedRocketry#595] opened 2017-04-30 02:36 UTC
So when in space inside my space station, utilizing the oxygen generators with carbon scrubbers the resultant atmosphere is fairly unreliable, randomly cutting out before quickly coming back every so often and giving me a dose of vacuum damage randomly. I've tried fiddling with the config settings with no change in this. Is this a bug?

**Comment by zmaster587** [comment] 2017-04-30 02:39
I've not encountered this at all over hours of testing time.  Can you
verify it's getting enough power and you don't have a door opening and
closing somewhere?
Could it be something on the station? What if you use only AR and non-tile
entities in the sealed area?

**Comment by DarkwarriorJ** [comment] 2017-04-30 02:52
Thanks for the prompt reply zmaster. I'm currently trying to replicate the problem on a single player test world - the world I'm having problems in is my multiplayer server. The station in question does have multiple things which might cause it - I recall for a while, stairs and slabs had some problems though I believe that was in a previous version. My current suspects are other mod's blocks and things such as hoppers. I can confirm that nothing is opening/closing in the sealed off part of the station, and as for power it seems to be getting enough - full power bar and all, though that still might be it maybe.

**Comment by DarkwarriorJ** [comment] 2017-04-30 03:01
On singleplayer, hoppers seem to be causing no problems. Neither do other mod's blocks either actually. The original suspects, stairs and slabs, also don't seem to be it, so it seems this problem is multiplayer server based.

**Comment by zmaster587** [comment] 2017-04-30 03:03
That is odd, are your settings for atmosphere calculatation the same on
both?

**Comment by DarkwarriorJ** [comment] 2017-04-30 03:11
Can confirm, the settings are identical. I was going to check to see if I can yet again replicate the problem on my server, but apparently some other mods unrelated to this one just decided to conflict all of a sudden and permacrash my world :/ Will make a new server to test in

**Comment by DarkwarriorJ** [comment] 2017-04-30 03:33
It seems it might be a bug local to my old server, because trying to replicate it on a new server doesn't seem to be happening. This is highly confusing though.

**Comment by DarkwarriorJ** [comment] 2017-04-30 14:44
Alright, testing on another world, I managed to get the bug to happen, though it seems that it flickers fast enough to not deal any damage. Things this bug does seem to highly correlate with include lag and station size; particular blocks don't seem to be doing anything. Especially lag, I think.

**Comment by DarkwarriorJ** [comment] 2017-04-30 14:56
I'm beginning to suspect that the problem is not size so much as adjacent rooms which are not oxygenated. Might that play a factor?

**Comment by zmaster587** [comment] 2017-04-30 17:15
That's odd indeed... what atmosphericCalculationMethod are you using?  Particularly is it 1 or 3?

**Comment by DarkwarriorJ** [comment] 2017-05-03 00:39
Thus far, I have attempted it on all four and ran into the same issues on the server; and the same lack of issues on clean new worlds without lag. For the server I've switched to just turning off atmospheric effects mainly due to the lag that seems to occur when trying to oxygenate a large chunk of my space station. Oh! I've also noticed that at certain camera angles, birch chests aboard my station turn green, and another friend of mine reported seeing random numbers on the blocks. Did I accidentally turn on some sort of debug mode or something?

**Comment by zmaster587** [comment] 2017-05-03 00:58
The birch chests turning green sounds like something is not cleaning up during render, same thing could be causing the numbers to appear.  In the case of the numbers something is probably trying to render txt inworld and not changing the texture back to the block texture map.

Anyway, knowing what atmosphericCalculationMethods this issue is occuring with is critical to tracking it down because each of the atmosphericCalculationMethod values run different code.

**Comment by zmaster587** [comment] 2017-05-07 05:09
I did find something that might be relevent.  I noticed if a metadata changes on a block in an unsealed area it causes nearby sealed areas to unseal and seal in a single tick.  Maybe it's related?

**Comment by zmaster587** [comment] 2017-05-07 05:33
What version are you running?

**Comment by joshuafcole** [comment] 2017-05-20 20:31
I can reproduce the error on version 1.1.7. Interestingly, one section of the station has no issues staying pressurized, while two others (of identical but mirrored layout) do. To try and minimize the difference I built a small box around the faulty vents and even at a 3^3 box wasn't able to get them to stop flickering. I'd be happy to try a test build if it hasn't been released yet.

**Comment by zmaster587** [comment] 2017-05-20 20:36
Can you give it a shot with one of the 1.2.x builds?  I remember fixing some issue where blocks outside the sealed area would affect the seal if changed.

**Comment by joshuafcole** [comment] 2017-05-20 20:42
Working perfectly now, thank you.

**Comment by zmaster587** [comment] 2017-05-20 20:43
Alright, good.  Thanks for testing!

**Closed by zmaster587** 2017-05-20 20:43 UTC
Labels: Unconfirmed Bug
