### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Tdrake02** [zmaster587/AdvancedRocketry#98] opened 2016-03-05 19:54 UTC
I have a lot of mods but still wonder what my problem is. Please tell me, Thankyou
[crash-2016-03-05_11.44.57-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/159996/crash-2016-03-05_11.44.57-client.txt)

**Comment by wormzjl** [comment] 2016-03-05 21:37
Duplicate of https://github.com/zmaster587/AdvancedRocketry/issues/33
Don't use incgc

**Comment by Tdrake02** [comment] 2016-03-05 21:59
What is incgc

**Comment by zmaster587** [comment] 2016-03-07 02:08
Try changed the dimention ID for the space stations in the Ar config (spaceStationId=x) to something else

**Comment by Tdrake02** [comment] 2016-03-07 02:09
Thank you. Now it is working

**Closed** 2016-03-07 02:10 UTC
