### ISSUE TITLE
Rocket lands in random spot on returning to Earth,  not on launch pad

### ISSUE THREAD

**Issue by weedenbc** [zmaster587/AdvancedRocketry#770] opened 2017-07-05 23:48 UTC
I've got a space station in orbit above Terra that I can travel to/from no problem. However, when my rockets return to Terra, they land on a beach several hundred meters from my launching pad. Is that designed on purpose?

**Comment by C1ffisme** [comment] 2017-09-25 20:42
From my experience, the space station has a default location at x: -1500 z: -1500. Rockets normally land at this spot on planets.

This is annoying, because it means that upon trying to land, you normally have to trek to your base, which is most likely near spawn.

I think the best solution to this issue is to have "landing pads" for rocket landings that you can select from a GUI before you leave the Space Station dimension. This is also useful if you don't want to land in or near an opponent's base on the same planet.

**Comment by dmodoomsirius** [comment] 2019-03-03 23:33
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by C1ffisme** [comment] 2019-03-04 01:05
![2019-03-03_18 57 36](https://user-images.githubusercontent.com/9893266/53704916-3ad01a80-3de6-11e9-942e-7e8f5e6a24e8.png)

From the top:
- Launching from Earth to a newly created space station puts the player at -1536, -1536 in the space dimension where the station is centered. Bizzare.
- Landing back on Earth after reaching the station does not immediately cause problems: The player will still land near the original launch site.
- Going back to the station, no problems.
- Create a Warp Drive and go to another planet.
- **Upon landing on a different planet,** the coordinates you land at are identical to the coordinates the rocket is centered at on the station.
- Fly back up to the station
- Going back to Earth, the rocket lands at the original launch pad again??

**Comment by zmaster587** [comment] 2019-03-04 01:27
That's expected behavior, the station has no way of knowing where the user intends to land on a new planet because it has no record of where the user took off from on said planet.

Space stations all share a single dimension so as not to exhaust the dimensions minecraft has available to use, to get around that, stations are separated spatially (hence the -1536, -1536).

Because the rocket was originally launched from Earth when it goes to the space station, it IS possible to know where the player intends to land.

**Comment by C1ffisme** [comment] 2019-03-04 01:50
Personally, I'd prefer a system closer to space stations, but with a few extra features:

- For every dimension, the game keeps a list of docking pads in that dimension.

- These pads can either be public or private. Private pads require a password in order to unlock.

- When you reach a sufficient height on a space station biome, the game pops up a dialogue of these docking pads unless none are available.

- If none are available, the rocket will attempt to land on a random spot within 300 blocks of the origin. (Enough space that if multiple rockets land, they shouldn't land on top of each other.)

- The rocket will save this area as the default landing spot for that planet and will land there if no docking pad is specified/no docking pads are available.

- In addition to these, a planet can be defined as "dockLandingOnly", so the rocket will query the player for a docking station/password before liftoff. If none exist, this setting will be overridden. If only private ones exist, however, the player will need to find a password before he can land there. This is useful for adventure maps.

- Possible optional addition: In order for a docking station to receive passwords and for a space station to send them, a radar dish/communications array block is required which can also serve some cosmetic purpose?

- CoFH Security support would be nice too, but I don't think it'd be as necessary.

**Comment by maladaptly** [comment] 2019-07-07 13:28
First two times I went to my new space station, I went Earth -> station -> directly back to Earth. Both times the rocket wound up at -1536,-1545, approximately 3km from home, where it was launched and where the only valid docking pad in the overworld exists. This is on 1.5.0-139.

Based on the comments in #1019, a player should, in theory, be able to work around this by programming a linker to a docking pad at their base, putting it in a docking pad underneath the spacecraft at their station, and then launching without an ID chip. But it appears #1019 has regressed, as while the ship did go to the dimension specified by the linker, it landed at -1536,-1545 all the same.

In the short term, I'd make rockets store a "home" dimension and coordinates, which is the site at which they were built, and returning to its "Home" dimension defaults to those saved coordinates.

Longer term, the new permutation of #1019 should be fixed, and Planet Id Chips should optionally store coordinates. Proposals:

* The guidance computer UI would have a "save this location" option, programming the current planet and coordinates into the slotted chip.
* Docking Pads would have an additional UI feature to directly program planet ID chips with their coordinates.
* Since choosing a new planet is now a potentially destructive operation, the planet selection screen will show a warning when about to reprogram a chip with saved coordinates.
* Launching using a planet ID chip that does *not* have coordinates programmed would make the rocket land at deliberately randomized coordinates, irrespective of its coordinates when it was launched.

**Comment by IMarvinTPA** [comment] 2019-07-21 19:42
Yes, #1019 has apparently regressed.  I just tried today with AR 1.12.2-16.0-159.  The rocket is taking the dimension ID of the linker in the Landing Pad.  I cannot do same-dimension hops.  I was trying to do a repositioning cruise to move the rocket out of the builder pad over to a basic pad.  The rocket just went up and down.  I tried putting a landing pad on orbiting dimension (Void dimension setup as another "moon" over the overworld.) and it came down at the same coords that it took off from rather than the other corner.
For the love of Pete, just let us put the linker in the guidance computer and go there.

IMarv

**Closed** 2020-04-11 00:04 UTC
Labels: Unconfirmed Bug, no-issue-activity
