### ISSUE TITLE
Crash with Fluid Renderer

### ISSUE THREAD

**Issue by teamMK** [zmaster587/AdvancedRocketry#750] opened 2017-06-26 06:45 UTC
Hi, I got a crash with codechicken renderer and your fluids, I dont know wich mod causes the  error:

```

java.lang.ClassCastException: net.minecraftforge.fluids.capability.templates.FluidHandlerItemStack cannot be cast to net.minecraftforge.common.model.animation.IAnimationStateMachine
	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:70)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:283)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:230)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:70)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:283)

-- Item being rendered --
Details:
	Item Type: zmaster587.advancedRocketry.item.ItemBlockFluidTank@4ed555be
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:230)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)


,,,

**Comment by paradoxchane** [comment] 2017-06-26 14:37
The same problem... when deleted Adv Rockertry it helped but, i want to have this mod in my modpack.

**Comment by sandalle** [comment] 2017-07-05 22:22
I think this is a duplicate of #721, #735, and https://github.com/zmaster587/AdvancedRocketry/issues/763 , can you try the fixed build from one of those?

**Comment by dmodoomsirius** [comment] 2019-03-03 23:25
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Closed by dmodoomsirius** 2019-03-03 23:25 UTC
