### ISSUE TITLE
non obtainable blocks

### ISSUE THREAD

**Issue by stevehello166** [zmaster587/AdvancedRocketry#2025] opened 2021-03-26 20:54 UTC
## Version of Advanced Rocketry

most recent 1.16.5 as of now
## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N

## Version of LibVulpes
Current release 1.16.5-1.0.1-2

## Version of Minecraft
1.16.5

## Does this occur without other mods installed
- [x] Y

>If Y, what is the MINIMUM set of mods required.
Mekanisim, ex nihilo sequentia, gaia dimension, gravestone, immersive engenering, iron chest, jei, journeymap, mekanisim generators, mystical agrulculture, oreexcavation, pamshc2, pneumaticcraft, powah, projectE,rftools, storage drawers, tesseract, thermal series,waystones,woot

## Crash report and log, or VisualVM snapshot (if applicable)
>http://pastebin.com is a good place to put them
>crash reports that are put in the issue itself are impossible to read

> If it's an issue involving lag, please submit a VisualVM sampler snapshot.  Mods like lag goggles cannot provide all of the information needed to debug lag in any useful capacity.
> For more information on how to create a snapshot, please see "How to Run CPU Sampling" [here](http://greyfocus.com/2016/05/visualvm-sampling/).  Then export the snapshot as an .nps.  You may have to zip it since github is weird, then please upload it here.

## Description of the problem
most of the advrocketry blocks do not drop their blocks when broken

**Comment by FynnWaelsing** [comment] 2021-03-28 15:43
This sounds like a duplicate of #2014

**Comment by FynnWaelsing** [comment] 2021-04-01 15:31
This appears to be fixed in the latest LibVulpes (LibVulpes 1.16.5-1.0.1-8 build -8 for 1.16.5) and AR (Advanced Rocketry 1.16.5-1.7.1-5 build -5 for 1.16.5) versions

**Comment by zmaster587** [comment] 2021-04-01 23:45
> This appears to be fixed in the latest LibVulpes (LibVulpes 1.16.5-1.0.1-8 build -8 for 1.16.5) and AR (Advanced Rocketry 1.16.5-1.7.1-5 build -5 for 1.16.5) versions

Thanks for replying!  That's good to hear, I forgot to tag this issue, but it should be fixed in that version

**Closed as completed by zmaster587** 2021-04-01 23:45 UTC
Labels: Unconfirmed Bug
