### ISSUE TITLE
Crash when key set to "\"

### ISSUE THREAD

**Issue by Derpford** [zmaster587/AdvancedRocketry#1563] opened 2019-04-11 04:50 UTC
## Version of Advanced Rocketry
1.5.0.-134
## Have you verified this is an issue in the latest unstable build
Have not verified
## Version of LibVulpes
0.4.0.-52
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
https://pastebin.com/UiFLjHgv

## Description of the problem
While cleaning up my keybindings, I set the Toggle RCS key to `\`. However, upon loading a world and pressing a key, I get the above crash. It appears that `\` is not one of the keys that Advanced Rocketry checks for properly.

**Comment by Silfryi** [comment] 2019-04-21 01:00
I cannot reproduce this, can you give more specific conditions?

**Comment by Derpford** [comment] 2019-04-21 17:09
I'm running Minecraft 1.12 with Forge 14.23.5.2815, on OpenSuse Tumbleweed
Linux.

**Comment by CvoidWyvern** [comment] 2019-06-01 21:11
One of my modpack's players have also experienced this crash, when setting Open Rocket GUI to mouse 5, or other mouse buttons. Crashes the singleplayer world after exiting the menu, and crashes on world load as long as it is set.
Forge 14.23.5.2836, Advanced Rocketry 1.5.0.-139
https://paste.dimdev.org/gonunexako.mccrash

modpack: https://minecraft.curseforge.com/projects/dragonbox/files/2718492

**Comment by zmaster587** [comment] 2019-06-01 22:05
can you replicate the issue with just AR, if not, what's the smallest set of mods you can replicate it with.
As far as I can tell from the crash report, it looks like an issue from the underlying engine.  LWJGL should not be throwing errors when checking to see if a key is pressed.

**Comment by CvoidWyvern** [comment] 2019-06-02 21:54
Yes, here's the crashlog with only AR LibVulpes and Forge:
https://paste.dimdev.org/agilakezal.cs

**Comment by expeehaa** [comment] 2019-06-03 14:36
I had a similar problem in mod version 1.5.0.-138, but it occured when I tried to leave a rocket by using the shift key and one time after closing my inventory. 
This could be solved by setting every key binding of Advanced Rocketry to an unused key (I used the numpad keys).
For completeness sake here is my crashlog: https://pastebin.com/yD7zjfbK (This is a modpack based on the All The Mods 3 pack but since this similar issue exists I think it is unrelated to the other mods)

**Comment by zmaster587** [comment] 2019-06-04 02:56
I can replicate @CvoidWyvern's issue.  Though that makes sense since it's only meant to look for key presses.

**Comment by zmaster587** [comment] 2019-06-04 03:31
31d2058 should fix the issue

**Closed** 2020-04-04 00:04 UTC
Labels: bug, no-issue-activity
