### ISSUE TITLE
An issue using Thermos

### ISSUE THREAD

**Issue by MrNyeGuy** [zmaster587/AdvancedRocketry#345] opened 2017-01-15 17:56 UTC
I've tested from 1.0.3-1.0.6 version for the 1.7.10 build on a thermos server and it has the error I've listed below (I tested them on a forge server and it was fine).

The error occurs when I join the server.

Error: http://pastebin.com/yEEiVtSy

**Comment by dmodoomsirius** [comment] 2017-01-16 01:01
is this in the log file or a crash report?

Have you also reported this to the Thermos team?

**Comment by zmaster587** [comment] 2017-01-16 14:46
Is this only with AR and libvulpes?

**Comment by wormzjl** [comment] 2017-01-16 18:59
looks like an asm conflict -_-,,,

**Comment by wormzjl** [comment] 2017-01-16 19:48
Confirmed that crashes with only AR
Now I get the same log as MrNyeGuy, the last one is probably due to the interference of TFC (which has modified the same class)

**Comment by zmaster587** [comment] 2017-01-16 22:47
It shows closed rather than merged because there was a conflict I has to fix by hand .  I've got no experience with Thermos though so I may take a bit of time to fix this.

**Comment by zmaster587** [comment] 2017-01-16 22:53
I'm actually just going to remove the ASM for the player class entirely as it's part of a half built implementation to allow multiple players to mount on one rocket, however that feature is currently not anyway so I'm just gonna comment it out for now

**Comment by zmaster587** [comment] 2017-01-16 23:06
I've tested the patch with Thermos-1.7.10-1558-server and it seems to let me log in after the fix but not before.  i'll release the patched build now.  Let me know if anything else comes up.

**Closed by zmaster587** 2017-01-16 23:06 UTC
Labels: Mod Interaction, Unconfirmed Bug

**Comment by wormzjl** [comment] 2017-01-16 23:07
Thx for the fix :)

**Comment by zmaster587** [comment] 2017-01-16 23:09
No problem
