### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by dkmk100** [zmaster587/AdvancedRocketry#1799] opened 2020-04-06 01:12 UTC
There should be a config option to allow a rocket with a high amount of fuel (maybe require advanced engines?) to be able to travel between different planets in the same star system, and only require the warp core for travel between different star systems. This would enhance the options a pack creator has for balancing purposes.

**Comment by dmodoomsirius** [comment] 2020-04-06 03:04
Duplicate of #1798

**Closed by dmodoomsirius** 2020-04-06 03:04 UTC
Labels: enhancement
