### ISSUE TITLE
Server can't use jetpack.

### ISSUE THREAD

**Issue by Android-KitKat** [zmaster587/AdvancedRocketry#776] opened 2017-07-11 11:12 UTC
Jetpack can not open.
Server will have the following error.

Minecraft version: 1.11.2
Forge version: 13.20.0.2315

[server_20170711-17.28.16.log](https://gist.github.com/Android-KitKat/4257725b12142f16e19be5bb050a9237)

**Comment by zmaster587** [comment] 2017-09-15 04:45
What version of AR and libvulpes>

**Comment by JTK222** [comment] 2017-09-19 16:19
Same Issue on latest available versions. Forge 1.11.2.

**Comment by DarVillous** [comment] 2017-11-09 04:25
I am also having this issue
LibVulpes-1.12.2-0.2.6-universal.jar
AdvancedRocketry-1.12.2-1.2.5a.jar
forge-1.12.2-14.23.0.2517-universal.jar

[ARjetpack.txt](https://github.com/zmaster587/AdvancedRocketry/files/1456285/ARjetpack.txt)

**Comment by cad435** [comment] 2017-12-05 00:29
Problem still persists, using Advanced Rocketry 1.12.2-1.2.6-27, libVulpes-1.12.2-0.2.6-16-universal and forge 14.23.1.2559

(Im using Spongeforge too: 1.12.2-2529-7.0.0-BETA-2746)

error is the same as far as i can see: https://pastebin.com/b3e2caFV

**Comment by nicohdemus** [comment] 2017-12-09 15:09
I am having the same issue in 1.11.2 on the server. Works fine in singleplayer. I am using...
forge 13.20.1.2530
libvuples 1.11.2.0.2.6-universal
advanced rocketry 1.11.2-1.2.5a

**Comment by nicohdemus** [comment] 2017-12-09 15:10
`09.12 16:03:50 [Server] Server thread/FATAL Error executing task
09.12 16:03:50 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
09.12 16:03:50 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
09.12 16:03:50 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
09.12 16:03:50 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
09.12 16:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
09.12 16:03:50 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
09.12 16:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
09.12 16:03:50 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
09.12 16:03:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
09.12 16:03:50 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.InventoryPlayer.func_70440_f(I)Lnet/minecraft/item/ItemStack;
09.12 16:03:50 [Server] INFO at zmaster587.libVulpes.util.InputSyncHandler.updateKeyPress(InputSyncHandler.java:31) ~[InputSyncHandler.class:unspecified]
09.12 16:03:50 [Server] INFO at zmaster587.libVulpes.network.PacketChangeKeyState.executeServer(PacketChangeKeyState.java:45) ~[PacketChangeKeyState.class:unspecified]
09.12 16:03:50 [Server] INFO at zmaster587.libVulpes.network.BasePacket$BasePacketHandlerServer$executor.run(BasePacket.java:120) ~[BasePacket$BasePacketHandlerServer$executor.class:unspecified]
09.12 16:03:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
09.12 16:03:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
09.12 16:03:50 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
09.12 16:03:50 [Server] INFO ... 5 more
`

**Comment by Thutmose** [comment] 2017-12-10 16:37
That libvulpes issue should explain exactly how to fix this, there may be other places where similar client methods are called, which was the main reason why I posted the issue instead of a pull request

**Comment by zmaster587** [comment] 2017-12-27 05:38
Fixed in https://github.com/zmaster587/libVulpes/issues/26

**Closed by zmaster587** 2017-12-27 05:38 UTC
