### ISSUE TITLE
[BUG]Rocket assembly machine and chocolate crashes the server

### ISSUE THREAD

**Issue by SirEndii** [zmaster587/AdvancedRocketry#2074] opened 2021-04-29 16:40 UTC
[Please fill out the form below and delete the sections in square brackets after reading them]

## Version of Advanced Rocketry
- 2.0.0-10

## Have you verified this is an issue in the latest unstable build
- Yes

## Version of LibVulpes
- 1.0.2-18

## Version of Minecraft
- 1.16.5
- Forge: 36.1.13
- Chocolate version: 1.3.0-1.16.4

## Does this occur without other mods installed
- Yes, only this mod, lib vulpes and chocolate

## Crash report or log or visualVM (if applicable)
Stacktrace: https://gist.github.com/Seniorendi/184038f7f0150858a43feed517b7cfe3

## Description of the problem
The Server crashes with AR and Chocolate installed when we use a rocket assembly machine.

- Place rocket assembly machine with the launch pad and the structure thingy blocks.
- Use the machine to build the rocket
- Server dies with chocolate in it.

Already submitted to chocolate, but I thought I should, report it at here too:
https://github.com/alcatrazEscapee/Chocolate/issues/10

**Comment by SirEndii** [comment] 2021-04-30 22:47
Because you added this to the bug project, I will not close this. But i will just delete chocolate: https://github.com/alcatrazEscapee/Chocolate/issues/10

**Comment by zmaster587** [comment] 2021-05-06 01:01
Looks like a duplicate of #2029.

**Comment by zmaster587** [comment] 2021-05-06 01:06
Since it's a duplicate, and to keep things organized, I'm gonna post subsequent comments back on #2029

**Closed as completed by zmaster587** 2021-05-06 01:06 UTC
Labels: duplicate
