### ISSUE TITLE
Oxygen Vent Doesn't Require Oxygen

### ISSUE THREAD

**Issue by slappav** [zmaster587/AdvancedRocketry#1404] opened 2018-09-29 19:29 UTC
## Version of Advanced Rocketry
1.4.0-99 & -102
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.2.8-37
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
[insert here]

## Description of the problem
The Oxygen Vent works when it has power but no oxygen.

Seal off an area (3x2x2 on space station in my case). Place the Oxygen Vent inside the room and a power source on top of it. Disable redstone control. The room gets pressurized.

Also:
When the seal is broken, the area that was formerly sealed still has pressure.

Tested with atmosphereCalculationMethod 3, 2 and 0

**Comment by zmaster587** [comment] 2018-09-29 23:35
are you using CO2 scrubbers?

**Comment by zmaster587** [comment] 2018-09-29 23:41
I cannot replicate the issue where the area is still sealed after breaking a block, though I can confirm it will run without O2

**Comment by zmaster587** [comment] 2018-09-29 23:47
this'll be why it's not using gas, in very small rooms the amount of gas used will be less than 1mb.
```
	public float getGasUsageMultiplier() {
		return (float) (Math.max(0.01f - numScrubbers*0.005f,0)*Configuration.oxygenVentConsumptionMult);
	}
```

**Comment by slappav** [comment] 2018-09-30 07:59
Neat. Just confirmed that larger rooms do require O2. 

Would this work?
int amtToDrain = (int) Math.ceil(AtmosphereHandler.getOxygenHandler(this.world.provider.getDimension()).getBlobSize(this)*getGasUsageMultiplier()));

**Comment by slappav** [comment] 2018-09-30 08:37
The issue where the area is still sealed after breaking a block persists.

Is it supposed to happen the instant I break a block?
Breaking a block within the seal (that was there when the seal was created), creates an air block with vacuum. So the sealed area doesn't update at all.

By the way, what does the oxygen trace button do?

**Comment by zmaster587** [comment] 2018-09-30 09:06
When you say seal, do you mean the blocks names "seal"?  And if so, do you mean breaking the block in the center of the 4 seals or one of the seal blocks themselves?

The Oxygen trace button will create a visible cloud for areas that the vent is attempting to seal.  It's mostly meant to try to track down holes in space stations and such.  If the area is properly sealed it won't do anything.

**Comment by slappav** [comment] 2018-09-30 09:51
By seal I mean "the pressurized area" or "to pressurize" an area.  Maybe it's clearer to use those terms...

To summarize the sealed area not updating issue:
1. Activating the oxygen vent pressurizes the room if it is closed. If not, closing the room (like filling in a missing wall) immediately causes the oxygen vent to pressurize the room. (as expected)
2. opening up the room again (by breaking the wall) does nothing. I can walk in and out through the big hole in the wall and have 0atm on one side and 1atm on the other.
3. Let's say I have a column in the middle of a pressurized room, then break the column (room is still closed). Now, if I walk to where the column was, I have 0atm. The rest of the room (what was air blocks when I activated the vent I guess) still has 1atm.
4. When I have an open area that is pressurized (from point 2), the following happens when using different methods of reactivating the oxygen vent.
  - cutting and reapplying the oxygen supply - same area gets pressurized 
  - cutting and reapplying power (rf) - does not pressurize, get oxygen trace particles
  - lever on/off - does not pressurize, get oxygen trace particles

**Comment by zmaster587** [comment] 2018-09-30 16:55
What version of forge are you using?  I'm not able to replicate 2,3, or 4.

**Comment by slappav** [comment] 2018-09-30 20:33
forge-1.4.23.4.2705
libVulpes 0.2.8-37

I'm testing on an old laptop now. I'll probably try it on a server running the same pack next week.

**Comment by zmaster587** [comment] 2018-10-01 04:50
Looks like the ASM is broken on newer versions of forge

**Comment by zmaster587** [comment] 2018-10-01 07:34
Turns out this has been broken for months because the manifest was not being written correctly.  I was unable to replicate the above issues because my DEV env forces the class transformers to load anyway... Either way, it's fixed now.

**Closed by zmaster587** 2018-10-01 07:34 UTC

**Comment by slappav** [comment] 2018-10-01 17:19
Great! Thanks for your hard work. I love your mod.
