### ISSUE TITLE
1.12.2 Bucket event-Client crash when eating mushroom stew

### ISSUE THREAD

**Issue by DingoX3** [zmaster587/AdvancedRocketry#1185] opened 2018-03-02 02:33 UTC
Minecraft Version:
-1.12.2
Forge Version:
-2623
Advanced Rocketry Version:
-1.3.0-59
LibVulpes Version:
-0.2.8-27
**is this the latest curseforge build?**
no
#Please Pastebin crash 
---------------------
Crash Report: https://pastebin.com/qJt267sv
----------
Explain issue in detail:
craft vanilla mushroom stew. proceed to eat stew. crash to desktop

**Comment by wamc2017** [comment] 2018-03-02 02:51
This was fixed in 1.12.2-1.3.0-60, with commit https://github.com/zmaster587/AdvancedRocketry/commit/b4fefb2da9903d1972a0297413bd25c79a91279e ;)
Duplicate of #1179 #1177 #1178

**Closed** 2018-03-02 04:05 UTC
Labels: duplicate
