### ISSUE TITLE
Crash Upon World Load

### ISSUE THREAD

**Issue by HyperionNexus** [zmaster587/AdvancedRocketry#199] opened 2016-09-11 06:33 UTC
Whenever I try to load my testing world, I crash and get [this](http://pastebin.com/m7DwUNkc).

I do know I was testing asteroid mining and had the item output setup but when the rocket was empty, it launched again to who knows where. It did this as well when I came back from a space station until I broke the item output. It was fine up until I left SP but when I came back to do another test, it crashed.

This is on 0.6.4 due to it being on a server but I wasn't able to find an issue on it.

**Comment by TheGuyRunningSouth** [comment] 2016-09-16 16:30
Is this the whole crashlog, or is there a "Caused By:" line?

**Comment by HyperionNexus** [comment] 2016-09-16 23:26
From what I can tell in the log, no.

**Comment by HyperionNexus** [comment] 2016-09-17 17:00
Pack updated a few things including Advanced Rocketry and now the world loads fine.

**Comment by zmaster587** [comment] 2016-09-29 01:49
alright, since you said it's fixed ima close this.  I'll look into it anyway though see if it's some edge case.

**Closed by zmaster587** 2016-09-29 01:49 UTC

**Comment by zmaster587** [comment] 2016-09-29 01:51
oh, yeah, i did fix this.  There was an instance where it would be ticked before the world was finished loading resulting in an NPE
