### ISSUE TITLE
Space Travel Multiplayer Issues

### ISSUE THREAD

**Issue by Gorehid** [zmaster587/AdvancedRocketry#555] opened 2017-04-12 15:36 UTC
This is in the Invasion 1.0.4 mod pack. Opening an issue here with a link as suggested.
https://github.com/Darkosto/InvasionIssues/issues/147

What I and other players on my server are experiencing is as follows. The rocket you are riding appears to no longer exist after going through the loading system. You stop in place and can hit no buttons to do anything. It's not that the moon is dark it's that NOTHING exists after the load. Be it a space station you created or the moon. Now, this may be a specific issue with my server and nothing can be done about it. I do not know about that, but I am reporting it here in case it is not just us.

**Comment by zmaster587** [comment] 2017-04-12 15:47
Does the server time out if you wait 30 second.  What is CPU load like,
memory usage, network usage?
Admittedly I have not watched the stream yet but I'm on mobile currently.

 Have you checked logs to see if any errors are printed when changing
dimensions?

From your description it sounds almost like the server has halted.  Though
I can't garuntee that's the case without more info.

**Comment by Gorehid** [comment] 2017-04-12 16:02
The server does not time out. Other players continue to play as normal. The RAM sits at around 3.7GB of 6GB available. CPU usage is about 27% total used. As far as network usage all I can say is low usage. There two people online.

As far as I can tell from the logs the only issue, had currently, is with a different mod and that's a non vital issues with The One Probe.

**Comment by zmaster587** [comment] 2017-04-12 16:58
Alright, so not likely a server performance issue.  Have you checked to see
if this issue also occurs in single player?

Also regrettably,  I cannot really understand your last paragraph there.

**Comment by GenDeathrow** [comment] 2017-04-12 17:01
That stream was just showing that it work in single. thats the pack dev and we havent had any ither servers report this issue.

**Comment by Gorehid** [comment] 2017-04-12 17:59
As GenDeathrow said, it works in single player.

**Comment by zmaster587** [comment] 2017-04-12 19:41
if you create a new server instance of the pack and test it does this occur there too?

**Comment by Gorehid** [comment] 2017-04-12 22:54
Created a new server from a fresh download of version 1.0.4 of Invasion. The achievements 'Moon Landing!' and 'One Small Step...' were given to me. The previously mentioned issue  still occurs. (I imagine the same applies to the creation of space stations but I did not try on this temporary server.)

**Comment by zmaster587** [comment] 2017-04-12 23:21
is there a way to get the pack without going through curse?

**Comment by Gorehid** [comment] 2017-04-12 23:29
Just [this](https://minecraft.curseforge.com/projects/invasion/files) (curse forge website) as far as I know.

**Comment by zmaster587** [comment] 2017-04-12 23:38
unfortunately that just contains specification to download files and foam.  I can download them manually I suppose.

**Comment by Gorehid** [comment] 2017-04-12 23:52
There is a secondary download at the bottom of each version that has the actual files. Give me a couple of minutes and I'll edit it in

**Comment by zmaster587** [comment] 2017-04-13 00:16
Just finished testing, I really don't know what's up.  I launched a server, built a rocket, flew to the moon, landed on it no problem.

**Comment by Gorehid** [comment] 2017-04-13 20:09
Well, I tried the design shown in the image. Still no luck. Other players have had the same issue, but I have no idea why. I'm out of ideas. Thank you for your time.

**Comment by zmaster587** [comment] 2017-04-13 20:12
One last ditch thing to try.  Can you send me the entire server folder?  I
don't need the world fIles other than the advRocketry folder.  The start
command used for the server may also be helpful

**Comment by zmaster587** [comment] 2017-04-13 20:13
If I still cannot replicate it with that then it's likely something with
the JVM bring run.

**Comment by Gorehid** [comment] 2017-04-18 20:03
Sorry, I have been busy. I will see about getting the files together. I will let you once I have them.

**Comment by dmodoomsirius** [comment] 2017-04-18 21:17
Hello. 
What is minecraft_openmod.jar? Is that the jar file you are running?

**Comment by Gorehid** [comment] 2017-04-18 21:19
That is something the hosting company uses. Nothing we actually use.

**Comment by dmodoomsirius** [comment] 2017-04-18 21:20
ok understood.  thanks for the prompt reply.

**Comment by AnsuzThurisaz** [comment] 2017-05-01 01:56
We have confirmed we too are having this issue on our dev server. What information can we provide to help?

**Comment by zmaster587** [comment] 2017-05-01 02:31
Version of AR, libvulpes, forge being used, location the rocket takes you in block coords.  Try it without any other mods installed.  Check to make sure it's not just the server or client lagging, output logs from both.  Try teleporting/falling down to the planet's surface to see if that is gone.

**Comment by AnsuzThurisaz** [comment] 2017-05-02 17:11
![2017-05-02_13 06 51](https://cloud.githubusercontent.com/assets/24760316/25629688/65b01480-2f38-11e7-820b-01934d61acc4.png)

So, we are in space! What I am thinking is going on here is anyone with mods that alter terrain generation might be hitting some serious hiccups on their hardware when trying to generate such complex landscapes in a never-before-loaded dimension. Our overworld needs to be pre-generated whenever we create a new test instance because the cost of custom worldgen is pretty heavy in our pack.

We are going to comb over the configs of anything that does custom world gen to see what we can do about disabling our custom world gen to whitelist only the dimensions we want said custom generation to appear in. This will likely alleviate or eliminate these hangups as well as make sure that the custom worlds/dimensions crafted by mod authors aren't being meddled with by other mods unless we tell it to.

Your thoughts?

**Comment by AnsuzThurisaz** [comment] 2017-05-02 18:11
I take it back. I was able to reproduce the bug returning to earth. Checked logs and there was literally nothing client or server side apart from the typical spam we get from such a heavy pack.

See video: https://youtu.be/LnfSOKzoefA

As you can see, the entry to Luna went fine. Returning to earth broke the same way that is being described by others not being able to land after loading into the new dim. when I disconnected/reconnected, you can see me happily sitting in the rocket, like nothing was wrong.

This mod will be a pretty significant cornerstone to our pack if we can get it working, And we want to. Badly.

**Comment by zmaster587** [comment] 2017-05-03 01:49
Does this bug occur all the time, some of the time or very rarely?  Is it possible to verify that the bug occurs with only AR and libvulpes installed?

Though I must also mention it looks very similar to a bug I encountered during the 1.7.10 => 1.10.2 upgrade where whether the rocket was moved to the planet before being teleported into place mattered because of MC chunk loading/unloading orders.  However that bug never occured between planets because the coordinates on both sides matched so the rocket never needed to actually be moved.  So because of that issue I'm wondering if maybe there's something in the pack screwing with moving entities between dimensions or altering some entity/chunk handling which is why I ask if it occurs without other mods.

**Comment by AnsuzThurisaz** [comment] 2017-05-03 11:53
To be perfectly honest, I am having a hard time regularly reproducing the issue.

Considering we have over 175 mods, this could get... tricky.

Do you happen to know what mods in the past gave you the most trouble? Or know of any specific mechanics or mods that might give us trouble so I can try to pear down the list to find the offender?

**Comment by eaanon01** [comment] 2017-05-14 22:35
I have this problem on my server and cant get to the moos. Only stuck at 1000 blocks above the moon and no serquance spash screen to go down. Running Invasion 1.0.7

**Comment by zmaster587** [comment] 2017-05-15 06:57
That would be helpful, if we could establish an ip and a time I'd really appriciate it.

**Comment by eaanon01** [comment] 2017-05-15 08:02
I sendt you am email

**Comment by zmaster587** [comment] 2017-05-15 22:24
As of now, I've still not recieved an email.  Maybe try PMing me on curse?

**Comment by zmaster587** [comment] 2017-05-17 17:55
Got the email, maybe it just took a while to get through or something?

**Comment by zmaster587** [comment] 2017-05-17 20:58
Appears to occur only on servers, bug also appears when using any interdimensional teleport command.

**Comment by zmaster587** [comment] 2017-05-17 21:06
turns out changing "allow-nether=false" to "allow-nether=true" in the server.properties fixes the issue

**Comment by eaanon01** [comment] 2017-05-18 07:46
Thank you for looking into it! ( btw I sendt to the wrong email first time )

**Closed** 2017-05-18 15:09 UTC
Labels: Mod Interaction, wontfix

**Comment by Darkosto** [comment] 2017-05-18 16:49
LOL! Seriously? That one setting is the reason behind this? Oh minecraft
