### ISSUE TITLE
Warping to stars always displays a black hole skybox

### ISSUE THREAD

**Issue by CJisDJ** [zmaster587/AdvancedRocketry#2052] opened 2021-04-10 13:41 UTC
When you warp to any solar system you should see star and other planets but you see only black hole
![2021-04-10_14 34 52](https://user-images.githubusercontent.com/82273054/114271639-aac41c80-9a12-11eb-9345-21e0f2891047.png)
To get there you need to click on solar system in warp controller and click select. Nothing happends but if you exit machine and open it again you can see something like this:
![2021-04-10_15 40 31](https://user-images.githubusercontent.com/82273054/114271717-1f975680-9a13-11eb-8b00-0e597eb73f12.png)

**Comment by voidsong-dragonfly** [comment] 2021-04-15 15:14
Duplicate of #1991

**Closed as completed by voidsong-dragonfly** 2021-04-15 15:14 UTC
Labels: Unconfirmed Bug
