### ISSUE TITLE
Pressing Oxygen Trace button on Vent crashes server

### ISSUE THREAD

**Issue by gluff95** [zmaster587/AdvancedRocketry#1098] opened 2018-01-24 21:05 UTC
Minecraft Version:
- 1.12.2
Forge Version:
- 1.12.2-14.23.1.2555
Advanced Rocketry Version:
- 1.12.2-1.2.6-50
LibVulpes Version:
- 1.12.2-0.2.7-25

https://pastebin.com/pvgNkq2x

Whilst on the space station, with the interior atmosphere depressurised (there was a hole in the station we think), pressing the "Oxygen Trace" button on the Oxygen Vent caused the server to crash. We cannot restart the server because it crashes whenever we do (the station is chunkloaded).

**Comment by zmaster587** [comment] 2018-01-26 07:51
Fixed with https://minecraft.curseforge.com/projects/advanced-rocketry/files/2523798

**Comment by zmaster587** [comment] 2018-01-26 07:52
dupe of #1080

**Closed by zmaster587** 2018-01-26 07:51 UTC
