### ISSUE TITLE
Crash when linking rocket and fueling station

### ISSUE THREAD

**Issue by ImToxik** [zmaster587/AdvancedRocketry#2082] opened 2021-05-02 16:54 UTC
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-2.0.0-10-universal.jar is the file used
## Have you verified this is an issue in the latest unstable build
Seems to be, yes
## Version of LibVulpes
LibVulpes-1.16.5-1.0.2-18-universal
## Version of Minecraft
Minecraft 1.16.5 Forge 36.1.0
## Crash report or log (if applicable)
https://pastebin.com/22i2AWNg

## Description of the problem
The problem comes into play when attempting to link an Assembled rocket multiblock with the fueling station to fuel it properly. Problem can be reproduced for me simply by shift-right clicking the fueling station, and then shift-right clicking the rocket itself. Every time I try, as soon as I click on the rocket, my game freezes, crashes to the launcher, and gives me the crash report linked above. I am using quite a few other mods but this seems to be AR specific as no other mods are being used except mekanism for power supply.

**Comment by voidsong-dragonfly** [comment] 2021-05-02 17:39
Duplicate of #2070

**Closed as completed by voidsong-dragonfly** 2021-05-02 17:39 UTC
