### ISSUE TITLE
Performance Issue with tiles

### ISSUE THREAD

**Issue by Sir-Will** [zmaster587/AdvancedRocketry#813] opened 2017-08-08 16:36 UTC
AdvancedRocketry-1.10.2-1.0.19
![](http://i.imgur.com/jMIAS5k.jpg)
![](http://i.imgur.com/1bVko5G.jpg)

**Comment by zmaster587** [comment] 2017-09-15 03:47
That appears to be a chunk load loop.  That's not good.

**Comment by dmodoomsirius** [comment] 2018-07-17 04:36
Duplicate of #1333

**Closed by dmodoomsirius** 2018-07-17 04:36 UTC
Labels: High Priority, duplicate
