### ISSUE TITLE
ONLY AR and Libv "A fatal error has occurred, this connection is terminated" when joining server

### ISSUE THREAD

**Issue by Mitchel75814** [zmaster587/AdvancedRocketry#1437] opened 2018-11-10 06:32 UTC
## Version of Advanced Rocketry
Unstable 112
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
Unstable 44
## Version of Minecraft
1.12
## Crash report or log (if applicable)
Server log:
[https://pastebin.com/4SAfwrcz](url)
Client Log:
[https://pastebin.com/svyD58MY](url)

## Description of the problem
I realize the guy before me has a similar issue but I thought I'd update. I am running a local server without sponge and when I try to join it boots me instantly with the "a fatal error has occurred, connection terminated" thing. No crash though. Also, it works perfectly on singleplayer and also works perfectly if I remove the advanced rocketry jar from the server and from the client so I know that it is the cause. I tried first with optifine and then without, same response. The modpack is a small custom one with about 20 some mods. I've been deleting the world folder in the server every time while running these tests so it generates a fresh one each time. I also tried setting the override overworld, planet, and station to false and it didn't work. I'm going to try to reduce the mod count further and see if its a mod interaction issue and then update.

**Comment by Mitchel75814** [comment] 2018-11-10 06:36
Okay I tested it with only AR and libvulpes and the same thing happened so definitely not a mod interaction issue.

**Comment by Mitchel75814** [comment] 2018-11-10 06:46
If its relevant, here are the server and client logs from only using the 2 mods.
Client:
[https://pastebin.com/fMdhGq5u](url)
Server:
[https://pastebin.com/Mh2WJ8nG](url)

**Comment by Mitchel75814** [comment] 2018-11-10 06:47
[](url)

**Comment by zmaster587** [comment] 2018-11-10 07:30
Looks to be a dupe of #1434

**Closed by zmaster587** 2018-11-10 07:30 UTC
