### ISSUE TITLE
[BUG] Game crash on startup.

### ISSUE THREAD

**Issue by eagleyes005** [zmaster587/AdvancedRocketry#1639] opened 2019-07-20 14:14 UTC
Here is the log:

[crash-2019-07-20_09.37.41-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/3413687/crash-2019-07-20_09.37.41-client.txt)

Using latest version. It seems to be some kind of incompability with TFC, but it just happens when AR version 1.12.2-1.6.0-160 build is installed. 
Edit: previous versions have the same issue.

**Comment by alcatrazEscapee** [comment] 2019-07-20 20:21
After much testing, I can reproduce this under very specific circumstances: with exactly the mods in the modlist, outside of dev environment. 

I can only reproduce the crash if I don't add anything whatsoever to the calling method - any log / try catch causes the crash not to happen. I can only conclude that some transformer has gone awry here and is having strange side effects as a result.

I can assure you that this crash is not something wrong with TFC -the error is an AR item returning itself as a capability when queried by stack.getCapability(CapabilityItemSize.CAPABILITY_ITEM_SIZE, null).  Which should not happen, as it violates the capability contract.

**Comment by Abdyman** [comment] 2020-01-31 11:56
is this something that can be fixed on your side(AR)?

**Comment by zmaster587** [comment] 2020-05-03 22:01
I don't think there's much that can be done on AR's side, `ItemSpaceArmor` will return `false` when checking `hasCapability` for `CapabilityItemSize`.  It seems more like `net.dries007.tfc.client.ClientEvents.onItemTooltip` should be checking that.

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.12.x/src/main/java/net/dries007/tfc/client/ClientEvents.java#L237

There should probably be a `item.hasCapability(CapabilityItemSize.ITEM_SIZE_CAPABILITY);` check here, that'll prevent this issue from coming up with non-AR mods too since it looks like it's assumed that every item will have that custom item size capability.

**Comment by zmaster587** [comment] 2020-05-03 22:05
> I can assure you that this crash is not something wrong with TFC -the error is an AR item returning itself as a capability when queried by stack.getCapability(CapabilityItemSize.CAPABILITY_ITEM_SIZE, null). Which should not happen, as it violates the capability contract.

I can assure you that it is a TFC side issue, not checking has capability first violates standard practice and directly is a cause of the issue.  From a code standpoint, while returning the object itself as part of the capability is not best practice, it's not the cause of this error.

**Comment by zmaster587** [comment] 2020-05-03 22:30
> is this something that can be fixed on your side(AR)?

Unfortunately it does not look like it.

**Closed** 2020-10-01 00:21 UTC
Labels: Mod Interaction, Unconfirmed Bug, no-issue-activity
