### ISSUE TITLE
[issue mod compatibility] gregtech 6 liquid oxygen

### ISSUE THREAD

**Issue by choum33** [zmaster587/AdvancedRocketry#1020] opened 2017-12-31 22:00 UTC
Minecraft Version:1.7.10
-
Forge Version:1.7.10-10.13.4.1614-1.7.10
-
Advanced Rocketry Version:1.7.10-1.2.4
-
LibVulpes Version:1.7.10-0.2.6-universal
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:

If i fill my spacesuit with oxygen or liquid oxygen (i tryed both) the O2 level doesn't fill and i can't breath on moon.
As i have Gregtech6 installed, it look like that advanced rocketry oxygen and liquid oxygen is replaced by gregtech one. Is there a way to solve this? (i mean maybe by config as you are not responsible for this issue ;)

My best regards

**Comment by zmaster587** [comment] 2017-12-31 23:28
Does this still occur in the latest versions or Advanced Rocketry and Libvulpes available on curse?

**Comment by choum33** [comment] 2018-01-01 10:30
Hi,

Do you recommand me to use the unstable version? Or to wait for a stabilized one? I don't want to destroy my world ;)

**Comment by zmaster587** [comment] 2018-01-01 18:02
I'd recommend the unstable version.  While it is marked as unstable, there've only been bugfixes between the stable and unstable builds so far, so it should be fine.  As usual though, I strongly suggest a backup just in case that way if something does go wrong you can resume where you left off before.

**Comment by choum33** [comment] 2018-01-02 14:41
Ok great, i'll test this this WE ;) (cross fingers)

**Comment by choum33** [comment] 2018-01-06 11:54
updated to the last version (adv rocket and libvulpes and GT6)
still unable to use my spacesuite.
I was able to load 100mB oxygen (lot liquid one) in spacesuite tank by walking on the charger and it stop and O2 level is not increasing. Liquid oxygen is not transfered from charger to spacesuite tank at all, nor used if tank filled by nother process (tank can't be placed in 2 first slot of the spacesuit anyway)

**Comment by zmaster587** [comment] 2018-01-07 05:53
Will investigate, thanks for testing on the latest version first.  There's a lot of things that get fixed and/or slip through the cracks with the changelog and it takes me a lot of time to test everything people throw at me.

**Comment by zmaster587** [comment] 2018-01-07 06:12
Turns out the issue is that gregtech uses "liquidoxygen" as the name of its oxygen and advanced rocketry uses "oxygen", so they're treated as totally different fluids

**Comment by zmaster587** [comment] 2018-01-07 06:30
Can you test the next build and report as to whether the issue is fixed?

**Comment by choum33** [comment] 2018-01-08 18:04
of course but only next WE ;) Thanks zmaster ;)
i'll keep you informed

**Comment by choum33** [comment] 2018-05-05 08:27
solved with adv rocketry 1.4.0-16 and gregtech 6.07.13 (maybe before)

**Comment by dmodoomsirius** [comment] 2019-03-03 23:44
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Closed by dmodoomsirius** 2019-03-03 23:44 UTC
Labels: MC1.7.10, Mod Interaction
