### ISSUE TITLE
Crash on World Generation with Bonus Chest

### ISSUE THREAD

**Issue by condensedapple** [zmaster587/AdvancedRocketry#230] opened 2016-10-07 19:04 UTC
Game crashes when creating a world **with "Bonus Chest" enabled**: [Crash Report](https://gist.github.com/condensedapple/fc1165538f2ec9ceec436ad49f976102)

**Comment by zmaster587** [comment] 2016-10-07 21:21
Should be fixed in next release, dupe of #221 and #219 
Thank you for at describing the conditions under which this occurs though, is very helpful comparatively.

**Closed by zmaster587** 2016-10-07 21:21 UTC

**Comment by condensedapple** [comment] 2016-10-07 23:36
Thank you for the quick reply. I will check the existing issues in the future.

**Comment by zmaster587** [comment] 2016-10-08 01:50
No problem!
