### ISSUE TITLE
Rockets Stacking

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#470] opened 2017-03-26 13:25 UTC
Built a space station and I had a friend come up to my station. I have the proper pads down and they each have linkers that are individually connected to each pad. However it is not recognizing the the pad is occupied.

**Comment by zmaster587** [comment] 2017-03-26 20:00
I'm having a bit of a hard time understanding the exact setup, you're describing so just to verify.  Do you have something like the following:
Pads A and B are on the space station
Pads C and D are on the ground

Pad C contains a linker programmed with the location of pad A, and pad D is likewise linked to B.  But you took off from pad C, your friend took off from pad D, and both of you landed on the same pad?

**Comment by Tyrantin** [comment] 2017-03-26 20:59
![2017-03-26_16 58 09](https://cloud.githubusercontent.com/assets/8041616/24335136/87d96d96-1245-11e7-9b44-dd57471b1493.png)
 Both took off from the same pad.

**Comment by Tyrantin** [comment] 2017-03-26 21:01
Do you have time to get on my discord?

**Comment by Tyrantin** [comment] 2017-03-27 09:39
Question, Will their be any updates within the next 3-4 days? Just wondering. Would like to move the modpack to Curse.

**Comment by zmaster587** [comment] 2017-03-27 14:10
I'll try to get back to you on everything at once.

Between you and your friend taking off, did you change the linker in the
pad you took off from?  Reason I ask is because it it expected behavior for
the rockets to land on each other if the same linker was used in the pad
the rockets are being launched from.  It was designed with flexibility in
mind for the player.  Rockets should only check if a pad is in use if no
linkers are being used to specify the landing location.

  If you did swa out the linker does the location the rockets landed also
happen to be the spawn location for the station?  Because if so that would
indicate the linkers are not working at all.

Hate to say this, but I currently do no have time to come on a discord
server.  The earliest I can probably come on would be Thursday or Friday
night due to my obligations not related to minecraft, animation, or game
development.

That being said I'm going to try to get a build pushed laterm today.
Though that's contingent on whether or not it takes me more than 15 minutes
to backport the new planet discovery system to 1.7.10.  If I don't hAve a
release by 6 hours from the time of posting.  That'll also probably not
happen until Thursday or Friday.

**Comment by Tyrantin** [comment] 2017-03-27 14:40
Ok, I used different linkers for each rocket. 

The reason I would like you to come to our Discord is to get some info and make some suggestions for advancement of your mod. It is one of the best Tek mods I have seen and would like to help you in advancement of your mod. Their is so many possibilities for your mod. Some of our ideas would propel you beyond the competition if you are willing to hear them. You can bring any of your​ Deb's you would like.

**Comment by DVorriose** [comment] 2017-03-28 03:12
Would it be possible to either print rocket(s) assigned on a pad block (Rocket Monitoring Station?) and/or pads assigned on a rocket (Guidance Computer) block?  Maybe in a linker?  It wouldn't really matter how, popup GUI, placed on block, called through NEI/JEI, whatever.

**Comment by zmaster587** [comment] 2017-03-28 05:08
@Tyrantin I'd be interested to hear them, will see if we can arrange something.  Though I will likely be unavailable for more than 4 or 5 minutes at a time until Friday or Saturday.

@DVorriose I'm not really sure how feasible that is currently, right now rocket destinations have kinda on odd heirarchy going on.  The way I've got it setup right now is that when a rocket takes off, nearby pads will check to see if a rocket is on top of it, if one is it overrides the destination, so rockets are not really assigned to pads per se.  The pads are really more assigned to dimensions and coordinates than anything.  The idea was that the user would be able to put signs down to remember which pad was which.  
Though I have plans in the future to be able to name and then be able to select named pads.

**Comment by Tyrantin** [comment] 2017-03-28 05:35
That's cool, understandable. Will spot for Friday then what is you TZ so we can plan accordingly.

**Comment by zmaster587** [comment] 2017-03-29 17:53
I'm EST, and should be available between 3EST and 5EST Friday

**Comment by Tyrantin** [comment] 2017-03-29 23:55
Awesome. I'm EST as well

**Comment by zmaster587** [comment] 2017-03-31 18:32
Perhaps a bit late to ask, but is there an ip address or something I can use to connect or some kind of identifier?

**Comment by Tyrantin** [comment] 2017-03-31 19:29
I will send you a message in curse with a link

**Closed** 2017-04-03 03:54 UTC
Labels: Unconfirmed Bug
