### ISSUE TITLE
[1.12.2] Fatal error on connecting to server

### ISSUE THREAD

**Issue by elijahlorden** [zmaster587/AdvancedRocketry#1004] opened 2017-12-26 03:15 UTC
After a server crash and some issues with another mod, players are now unable to connect to my server.  After examining the client logs, I found Advanced Rocketry to be the culprit.  Using Advanced Rocketry version 1.12.2-1.2.6-38.  The relevant lines from the console log:

`17:06:01	game	Caused by: java.lang.NullPointerException
17:06:01	game	at zmaster587.advancedRocketry.dimension.DimensionProperties.setStar(DimensionProperties.java:342) ~[DimensionProperties.class:?]
17:06:01	game	at zmaster587.advancedRocketry.dimension.DimensionProperties.readFromNBT(DimensionProperties.java:1190) ~[DimensionProperties.class:?]
17:06:01	game	at zmaster587.advancedRocketry.network.PacketDimInfo.readClient(PacketDimInfo.java:104) ~[PacketDimInfo.class:?]
17:06:01	game	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:210) ~[PacketHandler$Codec.class:unspecified]
17:06:01	game	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:192) ~[PacketHandler$Codec.class:unspecified]
17:06:01	game	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:101) ~[FMLIndexedMessageToMessageCodec.class:?]
17:06:01	game	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:38) ~[FMLIndexedMessageToMessageCodec.class:?]
17:06:01	game	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:4.1.9.Final]
17:06:01	game	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[MessageToMessageDecoder.class:4.1.9.Final]
17:06:01	game	... 65 more`

**Comment by zmaster587** [comment] 2017-12-28 06:20
Duplicate of #941 #956 #816 #760 
This one's been plauging AR for a while, the problem is I've still not been able to find a way to replibly cause the issue from a working server.
Do you have a backup of the world/advRocketry/temp.dat or the planetDefs.xml.  Is there something odd that happened, a server crash or something before this?  Any errors appear in console?  Can you take a working world and do something to make this happen again?

**Comment by DcNdrew** [comment] 2017-12-30 03:03
I have this problem too.
I don't know what I did, I just walked around in my house.

**Comment by LokeYourLord** [comment] 2018-01-03 06:25
I think I could help with this. I can upload my entire Server as a .rar file for you, and I can even tell you how exactly this can occur: All you need is to take a Portal Gun, and shoot it at the ceiling (in a cave or so) and then at the floor, your client will immediately crash but the server will not. I will also send you my client completely packed up. @zmaster587

**Comment by zmaster587** [comment] 2018-01-03 07:18
@LokeYourLord  While i can see the crash you experienced in the log then the resulting output from AR.  Sadly I cannot replicate either.  I went into a cave and shot the blue portal straight up onto a dirt ceiling, then the orange straight down onto a stone floor, I fell through the portals a few times and eventually ended up one block underground.

I tried simulating a crash by forcibly killing the client using the kill -9 command (the linux equivlient of "end process now" on windows) however even with that I could still connect to the server without issue.  I'll dig through your log files and see if I can find any other catalyst though.

**Comment by thecodejunkie** [comment] 2018-01-03 09:34
I think I am experiencing the same bug as the original poster. I have a Resonant Rise 4 (ATLauncher) single-player world running and yesterday when I tried to load it, it got stuck at 0% when loading the world. The log had a bunch of advanced rocketry exceptions like the one mentioned here. I've pretty much tried everything I could think of and the only thing that let me load my world was to remove this mod. Once I had done that, I could log back into my world.

Nothing strange happened the last time I played. I closed the game without any problems

**Comment by zmaster587** [comment] 2018-01-04 02:08
Removing the world/advRocketry/temp.dat and the planetDefs.xml in the same folder (or restoring those from backup) would also fix the world for future reference.

The issue is definatly real, I just can't get it to occur on my end.  Until I can make it occur on demand, there's not much I can do about it unfortunatly.

**Comment by dexslab** [comment] 2018-01-14 07:29
This issue happened right after my server crashed the planetDefs.xml got basically erased from its original size i just replaced i dont have the differences next time it happens i will definitely get you the differences

**Comment by zmaster587** [comment] 2018-01-14 09:17
@dexslab 

If it's happening every time, can you send me a copy of the entire setup?  world, mods, config, etc?  Also can you test with the latest version of the mod?  I've added a bit of debug code that may be helpful (it'll print something other than null, like star exception or something instead with additional info)

**Comment by dexslab** [comment] 2018-01-14 19:29
Here is my entire server directory nothing has been changed but i cannot connect with my client 

https://drive.google.com/file/d/1GW7r7uCmboAjK9yl-SzlRXV9Gvn1Ix45/view?usp=sharing

**Comment by dexslab** [comment] 2018-01-14 19:58
Just an update i removed the AdvRocketry Dim directory and it fixed the problem

**Comment by zmaster587** [comment] 2018-01-21 04:14
That would make sense, the issue appears to be something happening at some point with the server where it just "forgets" all the stars, then saves it to disk.  Deleting thr advrocketry dim directory would fix the issue because it forces the mod to regenerate the entire solar system from scratch.  Deleting the temp.dat and the planetdefs.xml also would suffice.

**Comment by dmodoomsirius** [comment] 2019-03-03 23:45
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Closed by dmodoomsirius** 2019-03-03 23:45 UTC
Labels: High Priority, bug, duplicate, help wanted
