### ISSUE TITLE
Well... finally a crash that corrupt my world at load rendering it unusable

### ISSUE THREAD

**Issue by jonabrv1965** [zmaster587/AdvancedRocketry#579] opened 2017-04-20 18:57 UTC
Here  the crash log... the crash happened 30 secs after the world load... it does not matter what I do ... simply "no response" and then the crash report....
[crash-2017-04-20_13.51.54-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/945187/crash-2017-04-20_13.51.54-server.txt)

**Comment by zmaster587** [comment] 2017-04-20 19:28
After some investigation it's looking like this can be caused by something else manipulating the loaded chunk list at the same time as the main thread.  This is likely caused by an interaction with another mod doing concurrent operations.  At least, if https://github.com/PaperMC/Paper/issues/313 is anything to go by.  Does this occur if all the mods other than AR are removed?  If not try an add the other mods back until you can find which one triggers it.

**Comment by jonabrv1965** [comment] 2017-04-20 19:54
Hi, to and insult to injury, I restored a backup and happened exactly the same... Seems something actually outside of the world itself... Yes I'm making two terraforms right now...

Uhmm. I have to figure out how to test with/without mods, because I do use all of them for something... so removing them would be traumatic...

For now I'm removing the AR config file (to force it to create a default one) and rename all the temporal directories used by AR (again to force the mod to create them with defaults). Ill let you know....

**Comment by jonabrv1965** [comment] 2017-04-20 20:00
Uhmm.. it seems that the removal of config and temporary dirs do work. Now I'm able to work with the world.... Remember, I had the config changed to allow terraforming without gases (to workaround another glitch past week, do you remember?).. so... I guess is related with terraforming.... (because as of now, with the new config is not running in aither of my two sites...I'm going to tweak the config back to allow terraforming without gases to see if can recreate the crash... Keep you posted....

**Comment by jonabrv1965** [comment] 2017-04-20 20:49
Now that I have tweaked the config to false in the fluids for terraforming, my two processes  seems not working, although there is no crash now but not terraforming either... I'm terraforming one planet from barren to earthlike, this planet is at pressure of 0.26, and is showing several blocks changes (to sand and dirt). Also I'm terraforming the earths moon, also pressure 0.26 but does not show any changes in the terrain blocks... Neither seems working now (the terraformers shows the led green, but there is no bars in the graphic section, after several minutes...)...

I have not changed mods nor added new ones this week... definitely have to be related to terraforming (specially with the planet which is showing changes in the terrain now)

I do backup daily, so I'm going to "rollback" to a one where the planet not be changed yet, and wait to this change occur and see what happened...

It's a challenge because if the error is triggered by the ending of a terraform process, I have a very little "window" to catch the offender mod...but I'll try to do my best...the issue is that my laptop takes forever to load MC...

**Comment by jonabrv1965** [comment] 2017-04-20 20:59
uhm... I found a saved world with pressure of .19 (no changes in the planet)... but now the terraforming process is not working.. (with or without the fluid requirement in the config....) running out of ideas...

**Comment by zmaster587** [comment] 2017-04-20 21:31
When you say it's not working, what exactly isn't working?  The terraformer
not turming on, the atm density changing?  The terraforming process when
passing critical points?

**Comment by zmaster587** [comment] 2017-06-06 17:44
appears fixed with 0d18c405b3234fd778fc430a3e76f98125fd9217 1fc8d232dcaa691202a9023a98edefbf5546dca2 and 164858776185e909adb9a33f208dde7f9f3dd566

**Closed by zmaster587** 2017-06-06 17:44 UTC
Labels: Unconfirmed Bug
