### ISSUE TITLE
Crash on server Ticking entity from enchantment 1.16.5

### ISSUE THREAD

**Issue by IchigoGames** [zmaster587/AdvancedRocketry#2022] opened 2021-03-26 03:05 UTC
## Version of Advanced Rocketry
AdvancedRocketry-1.16.5-1.7.1-4-universal.jar

## Have you verified this is an issue in the latest unstable build
- [x] Y

## Version of LibVulpes
LibVulpes-1.16.5-1.0.1-6-universal.jar

## Does this occur without other mods installed
- [x] Y i think so

## Crash report and log, or VisualVM snapshot (if applicable)
https://pastebin.com/fPFuWu9S

## Description of the problem

Crash on server from java.lang.NoSuchMethodError: net.minecraft..Enchantment.func_185262_c(I)Lnet/minecraft/enchantment/Enchantment;
	at zmaster587.advancedRocketry.util.ItemAirUtils.isStackValidAirContainer(ItemAirUtils.java:127) ~[advancedrocketry:unspecified] was not on server at the time so im not sure what enchantment caused it

Forge 36.1.2
Minecraft 1.16.5
Modpack The Final Frontier 2 5.5

**Comment by IchigoGames** [comment] 2021-03-26 03:07
let me know if anyone other info is need

**Comment by IchigoGames** [comment] 2021-03-26 03:10
![image](https://user-images.githubusercontent.com/11888162/112571807-cbf00080-8db6-11eb-9fab-77a65c50659f.png)
looks like theres only one enchantment that it could be as its the only one this mod adds

**Comment by IchigoGames** [comment] 2021-03-26 03:11
could be a conflict with the 
Apotheosis mod as it allows for enchments that are way more powerfull then normal aka lvl 40+ enchants

**Comment by zmaster587** [comment] 2021-04-01 23:49
It's possible, before build 5 of AR and 8 of libvulpes, I was also targetting an earlier version of forge, could you check to see if it's still a problem with the latest build?

**Comment by IchigoGames** [comment] 2021-04-02 17:54
ill try to test it its a hard one to test tho as im not 100% how it happened no one had the enchant yet but it still show that as the reason for crash would need to put it back on server to test it and i think its too soon for that. will try and recreate it in single player.

**Comment by zmaster587** [comment] 2021-04-03 03:45
I looked at it a bit more today, I think it might be server-side only, so if you cannot replicate the crash in single player, then I think I got the problem nailed down.

**Comment by zmaster587** [comment] 2021-04-03 04:09
Dupe of #2017 should be fixed for the next update

**Closed as completed by zmaster587** 2021-04-03 04:09 UTC
Labels: bug, duplicate, MC1.16
