### ISSUE TITLE
Losing Satellites

### ISSUE THREAD

**Issue by Dryxen** [zmaster587/AdvancedRocketry#682] opened 2017-06-05 13:12 UTC
It appears that you are unable to link to exsisting Satellites after the Server restarts,crashes, or unexpectantly closes.
using,
LibVulpes-1.11.2-0.2.3b-universal
AdvancedRocketry-1.11.2-1.2.0f

**Comment by zmaster587** [comment] 2017-06-05 22:12
That sounds almost as if the temp.dat file didn't save.  

If the server unexpectedly closes all bets are off due to the fact the game doesn't have a chance to save.  Though generally if the server crashes it will attempt to save the game before closing, but that depends on the nature of the crash, so there's not a lot I can do about those two situations.

That being said, I have tried linking to existing satellites after a standard restart on a server and have had no trouble relinking to the satellites in the satellite terminal.  If you have world save turned off you may also encounter this issue.  Just to verify, would it be possible to send the world/advRocketry/temp.dat on the server and say which particular satellite ID you were attempting to connect to but were unable to?

**Comment by Dryxen** [comment] 2017-06-05 22:54
heres a link to the temp dat from the original test server we were playing on.
http://s000.tinyupload.com/?file_id=80896739207305452252
i was able to reproduce this error on server stop and closing the server bat in a similar server environment ill try to reproduce it rq in a non sponge environment to make sure that it isnt sponge related,
thanks for the quick reply.

**Comment by Dryxen** [comment] 2017-06-05 23:46
quick reply i was able to reproduce it again with a basic forge server using 
forge-1.11.2-13.20.0.2282-universal just sending the stop command into console after building a new satellite.

**Comment by zmaster587** [comment] 2017-06-06 00:55
I see something very odd with the temp.dat right away.  The overworld appears to be missing from the file.  This would prevent satellites from being saved at all I think.  At some point I had moved satellites from being stored with the planet they orbit to just being stored with the overworld and given id of they planets they actually orbit.

Can you pastebin a copy of the advRocketry/planetdefs.xml file as well?  Is the world you are playing on intentionally set up to not have the overworld as a dimension that can be visited with AR's rockets and stations?

**Comment by Dryxen** [comment] 2017-06-06 02:00
there shouldnt be anything to change that on the test server i dont personnally manage it though on the forge server i set up its just defaults with advanced rocketry jei and the one probe.
heres the xml from the pack testing server https://hastebin.com/delobeqiju.xml
and the forge server https://hastebin.com/enegajitam.xml

**Comment by zmaster587** [comment] 2017-06-06 02:19
The Overworld definitely is missing as an entry.  So I think the problem is twofold, there should be an overworld entry in the XML unless there is some reason to prevent players from going to the overworld.  Second, advanced rocketry should force a save of the overworld.  I'll work on the 2nd one.

If you do want to add the overworld as a visitable planet, you can add https://pastebin.com/uVGhmVgC to the XML while the server is shut down and that should also fix the issue with the satellites.

**Comment by Dryxen** [comment] 2017-06-06 03:06
cool all add that rq and test it out thanks for squashing all the bugs so quickly =P

**Comment by zmaster587** [comment] 2017-06-06 17:06
No problem!

**Closed by zmaster587** 2017-06-06 17:06 UTC
Labels: Cannot Replicate, Unconfirmed Bug
