### ISSUE TITLE
 crash at startup

### ISSUE THREAD

**Issue by krisdeds** [zmaster587/AdvancedRocketry#216] opened 2016-10-05 21:31 UTC
[crash-2016-10-05_23.15.38-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/512376/crash-2016-10-05_23.15.38-client.txt)

**Comment by zmaster587** [comment] 2016-10-05 23:58
Duplicate of #215 shold be fixed next release

**Closed by zmaster587** 2016-10-05 23:58 UTC
