### ISSUE TITLE
Various problem with the space elevator.

### ISSUE THREAD

**Issue by Thysium** [zmaster587/AdvancedRocketry#988] opened 2017-12-14 19:45 UTC
Minecraft Version:
- 1.12.2

Forge Version:
- 1.12.2-14.23.1.2564

Advanced Rocketry Version:
- 1.2.6-7 alpha

LibVulpes Version:
- 0.2.7-19 alpha

Explain issue in detail:

- Texture problem on the block of the space elevator when the structure is finalized.
https://image.ibb.co/gCsyfR/2017_12_14_20_14_06.png

- The elevator becomes invisible if a block is present in the center of the elevator structure.
I add that the grass of the mod Better Foliage passes through the texture of the structure.
https://image.ibb.co/cy0Un6/2017_12_14_20_14_31.png
https://image.ibb.co/cARr0R/2017_12_14_20_14_41.png

- No collision on the roof of the lift cabin.
https://image.ibb.co/i1DbZm/2017_12_14_20_15_48.png

- The elevator hides the texts that appear on the screen.
https://image.ibb.co/j8nW0R/2017_12_14_20_13_53.png

- The energy column disappears when the player looks up from a certain height.
https://image.ibb.co/jKNyfR/2017_12_14_20_17_15.png
https://image.ibb.co/ee1fum/2017_12_14_20_17_17.png

**Comment by nonenothing** [comment] 2017-12-14 21:18
And more:
after some use elevator just begin to kill player (when start - shaking screen and when enter into space station dimension - kill by "hit the ground")
Every time.

**Comment by zmaster587** [comment] 2017-12-15 05:26
The first issue is a and issue with the model, will get around to fixing that eventually, though it's not a high prority since it's a render only bug.

The second issue is a duplicate of #938 and should be fixed with the space elevator in the next build

I'll look into seeing if i can add collision to the roof, though as it appears now it looks like enities can only have a single box for collision without some pretty deep edits to MC.  I was experimenting with it with rockets a while back, though implementation is rather difficult(couldn't figure out a way without messing around with the coremod mod) and the functionallity appears to break between MC versions.

The elevator hiding text looks like some kind of render order failure, though I wonder if the text also renders behind things like chests too.

The energy column disappearing unfortunatly is another thing that requires coremod modification since MC wont render chunks (or the entities in them) if you're too high up.  But since you're normally not that high up other than in a rocket or in a capsule, I don't think it's worth fixing due to the amount of effort involved.

@nonenothing can this be reliably replicated?  How many uses are required for this issue to occur?

**Comment by nonenothing** [comment] 2017-12-15 13:44
>How many uses are required for this issue to occur?
Not many - maybe 10 or so.
Here it is (mods, conf and saved world), see by yourself:
https://nofile.io/f/f8vN8DsECAo/minecraft.zip

**Comment by dmodoomsirius** [comment] 2019-03-03 23:46
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Closed by dmodoomsirius** 2019-03-03 23:46 UTC
Labels: Low Priority, MC 1.12.2, Unconfirmed Bug
