### ISSUE TITLE
releasing the content of a Lava Bucket into air crashes the game

### ISSUE THREAD

**Issue by ninjamask** [zmaster587/AdvancedRocketry#1184] opened 2018-03-02 02:15 UTC
Minecraft Version: 1.12.2
-
Forge Version: forge-1.12.2-14.23.2.2624.jar
-
Advanced Rocketry Version: AdvancedRocketry-1.12.2-1.3.0-59.jar 
-
LibVulpes Version: LibVulpes-1.12.2-0.2.8-27-universal.jar  
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report: 
----------
Explain issue in detail:
https://minecraft.curseforge.com/projects/forever-stranded-lost-souls/issues/186

releasing the content of a "Lava Bucket" crashes the game. testing showed that it happens if you point at an air block which has no solid blocks attached or in other words an air block enclosed with air

**Comment by wamc2017** [comment] 2018-03-02 02:52
This was fixed in 1.12.2-1.3.0-60, with commit https://github.com/zmaster587/AdvancedRocketry/commit/b4fefb2da9903d1972a0297413bd25c79a91279e ;)
Duplicate of #1179 #1177 #1178

**Closed** 2018-03-02 04:04 UTC
Labels: duplicate
