### ISSUE TITLE
Crash to Desktop issue

### ISSUE THREAD

**Issue by 88880** [zmaster587/AdvancedRocketry#1236] opened 2018-04-04 20:03 UTC
## Version of Advanced Rocketry
AdvancedRocketry 1.12.2-1.4.0-68
## Have you verified this is an issue in the latest unstable build
Yes, but the same thing happened in 1.4.0 67 too
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-27-universal
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
https://pastebin.com/inRzsqmK

## Description of the problem
Hello, I have a good amount of mods. The install works fine, then I add any advanced rocketry .jar into it and it crashes to desktop. I have industrial craft, 4 of the thermal mods, immersive engineering, nuclearcraft, etc. Thank you in advance :)

**Comment by zmaster587** [comment] 2018-04-05 02:52
Duplicate of #1235

**Closed by zmaster587** 2018-04-05 02:52 UTC
