### ISSUE TITLE
Data Cables don't pull/transfer data

### ISSUE THREAD

**Issue by CJL48** [zmaster587/AdvancedRocketry#617] opened 2017-05-07 20:55 UTC
With or without a redstone signal, I can't get the data cables connected to three satallite terminals to move data either to an observatory or to an astrobody data processor. Advanced Rocketry 1.1.7

**Comment by zmaster587** [comment] 2017-05-07 20:57
Does breaking/replacing a cable make it work?

**Comment by CJL48** [comment] 2017-05-07 21:46
I believe that I did try breaking and replacing cables. I eventually gave up and moved the data manually with the storage items.

**Comment by zmaster587** [comment] 2017-05-07 22:48
can you send a screenshot of the setup, or a replica of it?

**Comment by Leaveleaf** [comment] 2017-05-09 08:19
I have this bug too,they can't move data about Mass，Advanced Rocketry-1.7.10-1.2.0-12

**Comment by zmaster587** [comment] 2017-05-09 18:47
Can you post a screenshot of the setup?

**Comment by Leaveleaf** [comment] 2017-05-10 00:14
@zmaster587 I'm sorry ,the test server is close ,so i do it at a single world，their work。。

**Comment by Leaveleaf** [comment] 2017-05-10 00:30
ahhh! i find the bug，if a machine at the red circle，they will can't move mass！

**Comment by zmaster587** [comment] 2017-05-10 04:09
It may not be the machine, I'm wondering if it's the redstone, see what happens if you remove the redstone from on top of the circled machine.

**Comment by duncanwebb** [comment] 2017-05-20 11:28
This worked for me, when I broke the circled block but everything needed to be connected with a redstone signal before breaking the cable.

![image](https://cloud.githubusercontent.com/assets/4198031/26275412/efbefa1c-3d5f-11e7-93af-ef36ee6f7a4c.png)

**Comment by zmaster587** [comment] 2017-05-20 20:35
is that with 1.2.0 on curse or an earlier build?

**Comment by duncanwebb** [comment] 2017-05-21 09:12
It is the Forever Stranded version so 1.10.2-1.1.7

**Comment by zmaster587** [comment] 2017-05-22 15:50
Alright, would it be possible to test the same setup with a 1.2.0 build and see if it still misbehaves?  Reason I ask is i did do some work on it (#424) and it may or may not have fixed this issue as well.

**Comment by duncanwebb** [comment] 2017-05-23 17:15
I'm going to have difficulty testing this as once it works the NBT data of the blocks has changed and then it keeps working when reassembled. The order of assembly is also important but I can't remember in what order I built it. Any way I'll see if I can reproduce it with my current version and then try the same with the update and let you know, one way or the other.

**Comment by duncanwebb** [comment] 2017-05-23 18:14
Hi, I built a similar setup again and this time it worked first time, sorry I cannot reproduce the bug, I just placed the redstone torch down and the data was transferred without even pressing connect on the satellite terminal.

![image](https://cloud.githubusercontent.com/assets/4198031/26369153/1891aab6-3ff4-11e7-9eb3-910ff6fffcd8.png)

(Ignore the clocks to the right, they are for something else.)

**Comment by zmaster587** [comment] 2017-05-23 18:57
Alright, if it does come up in 1.2.x builds send me a poke.

**Comment by zmaster587** [comment] 2018-02-20 00:23
@Landstryder what version of the mod/minecraft?

**Comment by Landstryder** [comment] 2018-02-20 17:11
At the time of the message it was the latest version AR 1.2.6-49 and Forge 14.123.1.2590 but there are newer versions now so it may be fixed, just waiting for the modpack (Colonial Engineers) I'm playin to update.

**Comment by zmaster587** [comment] 2018-10-13 20:47
Data cable deprecated, use wireless transcievers instead

**Closed by zmaster587** 2018-10-13 20:47 UTC
Labels: bug
