### ISSUE TITLE
Crash when interacting with Rocket Inventories

### ISSUE THREAD

**Issue by Danickar** [zmaster587/AdvancedRocketry#992] opened 2017-12-17 16:01 UTC
Minecraft Version:
-1.12.2
Forge Version:
-14.23.1.2566
Advanced Rocketry Version:
-1.2.6-25
LibVulpes Version:
-0.2.6-16
**is this the latest curseforge build?**

#Please Pastebin crash
https://pastebin.com/kaWsHjXd
---------------------
Crash Report:
----------
Explain issue in detail:
Almost every time I try and interact with a rocket's internal inventory (chests, guidance computer, satellite bay) Minecraft crashes to the desktop.

**Comment by Danickar** [comment] 2017-12-17 17:04
In further testing there is a higher chance of being able to interact with the inventory if it is a brand new rocket, although still crashes a lot. I have been unable to access the inventory on a rocket that has made it into space and returned.

**Comment by zmaster587** [comment] 2017-12-21 04:12
does this occur without sponge?

**Comment by Danickar** [comment] 2017-12-22 02:39
Without Sponge it still does occur. We have been using the various hatches/unloaders to access the rockets internal inventories now.

**Comment by zmaster587** [comment] 2018-01-04 02:51
What about without buildcraft?

**Comment by zmaster587** [comment] 2018-01-07 18:48
dupe of #972

**Closed** 2018-01-07 18:54 UTC
Labels: Mod Interaction, duplicate
