### ISSUE TITLE
[1.11.2] Crash looking up fluid usages in JEI

### ISSUE THREAD

**Issue by Terpo** [zmaster587/AdvancedRocketry#735] opened 2017-06-18 12:10 UTC
https://gist.github.com/Terpo/a3177de313aa198fbe118be0960cd1a4
When looking up fluids in JEI the game crashes. (in only crashes for usages (U key))

forge: 2315
LibVulpes-1.11.2-0.2.5-universal.jar
AdvancedRocketry-1.11.2-1.2.2.jar

**Comment by sandalle** [comment] 2017-06-21 03:50
Found this via https://github.com/TheCBProject/CodeChickenLib/issues/57 , as I was going to open up a bug report against Code Chicken Lib or JEI as well. :)

[crash-2017-06-20_20.47.37-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1090287/crash-2017-06-20_20.47.37-client.txt)

**Comment by zmaster587** [comment] 2017-06-21 16:50
appears to be a dupe of #721 .  Should be fixed next build

**Closed by zmaster587** 2017-06-21 16:50 UTC
