### ISSUE TITLE
Torch Dupe

### ISSUE THREAD

**Issue by GoodBob** [zmaster587/AdvancedRocketry#633] opened 2017-05-14 19:54 UTC
So far i've done this on the moon and in a space station, both of which did not have any atmosphere. When attempting to pick up a torch with torches in hand, it 'breaks' the torch but leaves a torch in it's place. 

It might be related to the Extinguished Torch not being the same as a vanilla torch?

**Comment by zmaster587** [comment] 2017-05-14 20:51
Is that when breaking an extingushed torch or a normal torch?

**Comment by zmaster587** [comment] 2017-05-14 21:25
I've tried left-clicking a torch to break it and leftclicked an unlit torch.  In both cases the torch was broken in world and an item was dropped.  Is this not the same thing you did?

**Comment by GoodBob** [comment] 2017-05-17 01:31
When breaking an extinguished torch. Did you have a stack of torches in your hand as you broke it?

**Comment by zmaster587** [comment] 2017-05-17 03:02
not a stack of 64, but I did have a stack of 2

**Comment by zmaster587** [comment] 2017-05-17 03:08
Was it done on a server or single player?

**Comment by GoodBob** [comment] 2017-05-17 04:23
Hrmm, it wasn't a full stack when I did it. It was on a server,

**Comment by zmaster587** [comment] 2017-05-17 16:25
I tried it on a server as well, no different than my single player attempt.  Do you have any other mods installed?  Also I probably should have asked this earlier, but is this for MC 1.10.2 or 1.7.10?

**Comment by GoodBob** [comment] 2017-05-18 04:39
1.10.2 on the modpack called "All the Mods" so there are a few mods that could be causing the bug. I'll play around with them.

**Comment by zmaster587** [comment] 2017-05-18 14:57
Alright, I was testing with 1.10.2 and didn't think about it until tehn.  I guess the best course of action would be to check to see if it still occurs on your end without any of the other mods installed, that'll at least confirm whether it's a mod interaction.  If it keeps occuring with the other mods taken out then... some magic is happening somewhere and I'd need to figure that out.  If not then I guess we need to find the minimum set of mods where this occurs so we can figure out the interaction and hopefully stick a patch on it

**Comment by WesTroy** [comment] 2017-07-10 23:51
Just to restart the conversation: this does still occur on 1.10.2.

Installed only:
Forge 12.18.3.2185 (Recommended)
or Forge 12.18.3.2316 (Latest)
AdvancedRocketry-1.10.2-1.2.2
LibVulpes-1.10.2-0.2.5-universal
(default configs)

Steps to reproduce:
1. Go to the Moon.
2. With one or more torch(es) in your inventory, place one down on the surface.
3. Break it (even with your hand). By the time it lands, you will likely (~9/10 times?) have two.
4. Dupe/profit.

I did not test the other planets (too much work to get there each time in a small test environment!) Tested this today. Both Forge versions gave identical results.

Really a very minor issue, however (anyone can easily obtain countless torches anyway). Probably something to do with your extinguished-torch code.

Hope this helps. Excellent mod, by the way - love it to bits. It reminds many of us of the potential that WarpDrive had when it was active. Keep up the great work!

**Comment by zmaster587** [comment] 2018-01-27 04:35
Should have been fixed in the last 2 months or so, can no longer replicate it at least

**Closed by zmaster587** 2018-01-27 04:35 UTC
Labels: Unconfirmed Bug
