### ISSUE TITLE
[1.12.2] Machine Item Forms Have Broken Textures

### ISSUE THREAD

**Issue by EmosewaPixel** [zmaster587/AdvancedRocketry#987] opened 2017-12-14 13:00 UTC
Minecraft Version:
- 1.12.2
Forge Version:
-14.23.1.2562
Advanced Rocketry Version:
-1.2.6-7-UNSTABLE build -7
LibVulpes Version:
-0.2.7-19-UNSTABLE build -19
Explain issue in detail:
 Just as the title says, in inventories and in your hand, all the multiblock "controller blocks" have broken textures:
![image](https://user-images.githubusercontent.com/25333164/33993506-14f08268-e0d7-11e7-8fd6-2e64bfc2cb78.png)
![image](https://user-images.githubusercontent.com/25333164/33993512-1c050358-e0d7-11e7-8503-b7956c6955c7.png)

**Comment by zmaster587** [comment] 2017-12-15 04:23
Are you using a texture pack at all?

**Comment by EmosewaGamer** [comment] 2017-12-15 05:19
Nope.

**Comment by zmaster587** [comment] 2017-12-15 05:56
I'm unable to replicate the issue on my end.  Does this still occur if everything except AR, libvulpes, and JEI are removed.  If so, does it still occur if you redownload both mods?

**Comment by EmosewaGamer** [comment] 2017-12-17 19:19
Ok, by the looks of it, it's mod interaction. I'll have to look into it more to find out which though.

**Comment by MokahTGS** [comment] 2017-12-19 22:39
Looking at the loot Bags issues it doesn't seem to be caused by loot bags...just a symptom of the problem caused here.

**Comment by EarthwormO** [comment] 2017-12-21 13:40
I also have this problem in 1.12.2 Using the latest build.  You can see my Paste from the Chem Reactor Crash to see the mods i am running:

https://pastebin.com/iWp2Zt7U

**Comment by zmaster587** [comment] 2017-12-22 06:15
@EarthwormO Chemical reactor was fixed in build 38, which should be out now.  Also does this occur with only advanced rocketry and libvulpes and forge.  I still cannot replicate it on my end, and given youtube videos from people using the latest builds, this issue is not universal.

**Comment by EmosewaGamer** [comment] 2017-12-22 07:42
Did you miss my last comment? It occurs when the mod is installed together with Lootbags, but seems to be on LibVupes' side.

**Comment by pixzi** [comment] 2017-12-22 13:40
Experiencing the same issue with the missing textures. Also have Advanced rocketry and/or LibVupe's messing up the common lootbag texture. 

I've tested with and without a texturepack and i've ruled out any other mod.
 As soon as i load these 3 together i get no textures and the incorrect one for the bag.

**Comment by Gamertech** [comment] 2018-04-24 07:01
I'm also getting this bug, but it was triggered by installing UniDict. Booster Rockets and Flexible Tools aren't installed.

1.12.2
Forge Version:
14.23.3.2651 to 14.23.3.2673
Advanced Rocketry Version:
1.4.0-77
LibVulpes Version:
0.2.8-29-universal

**Comment by zmaster587** [comment] 2018-04-29 21:51
fixed in build 79 and corresponding libvulpes

**Closed by zmaster587** 2018-04-29 21:51 UTC
Labels: MC 1.12.2, bug
