### ISSUE TITLE
Crash on Gas ships return. :/

### ISSUE THREAD

**Issue by Tyrantin** [zmaster587/AdvancedRocketry#501] opened 2017-04-02 16:06 UTC
[crash-2017-04-02_10.03.28-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/888463/crash-2017-04-02_10.03.28-server.txt)

**Comment by zmaster587** [comment] 2017-04-02 17:24
Duplicate of #462 Should be fixed in the build I'm in the process of uploading

**Closed by zmaster587** 2017-04-02 17:24 UTC
