### ISSUE TITLE
Lens Block & Precision Assembler

### ISSUE THREAD

**Issue by ZexMaxwell001** [zmaster587/AdvancedRocketry#882] opened 2017-10-25 05:48 UTC
MC - 1.10.2
ADVR -1.2.4
LibV 0.2.5
Forge 12.18.3.2511
Mods: All The Mods 1 (modpack)

I placed 3 glass blocks with 3 lens and iron rod into the Precision Assembler's input hatch. the machine doesn't take the material to make a lens block. when I substitute the iron rod with an iron axle, the machine eats the items and doesn't produce the lens block.

**Comment by Thutmose** [comment] 2017-10-26 03:30
what is the multiplier listed on the interface for the precision assmbler? This could be a duplicate of #881

**Comment by ZexMaxwell001** [comment] 2017-10-26 04:30
I was thinking the same thing after i posted. But I'm not well versed in code so I figured to wait and see what others thought.

the PA is running at a speed of 330.87x. using 2 copper coils and 2 advanced motors.

**Comment by Thutmose** [comment] 2017-10-26 14:25
You can test if it is the same bug by downloading the nbtedit mod, then using then nbtedit command on the precision assembler block itself, if there are any entries in the output stacks list, and completion time says 0, then it is the same bug

**Comment by ZexMaxwell001** [comment] 2017-10-26 20:24
it shows that the completion time is -1

**Comment by Thutmose** [comment] 2017-10-26 21:20
Does it have anything listed in the outputstacks list? This also has to be checked with the materials in the input hatch

**Comment by ZexMaxwell001** [comment] 2017-10-26 22:14
https://imgur.com/a/zhrdL

**Comment by Thutmose** [comment] 2017-10-26 22:18
See how it has completionTime 0, that is what is making it not output.  Try editing the value of timeMult to 0.2 or so, then see if it works (might also need to remove the assembler and remake it, then edit timeMult)

**Comment by ZexMaxwell001** [comment] 2017-10-26 22:54
ok, I changed the completion time to 1 and timemulti to 0.2 and it made the item. however, the scope of the issue is mod integration. I have to make a iron axle from crossroads for the AR to accept the items. it wont take an iron rod from substratum.

**Comment by Thutmose** [comment] 2017-10-26 22:56
Is the iron rod from substratum ore dict registered to the same string as the iron axel/lib vulpes iron rod thing?

**Comment by ZexMaxwell001** [comment] 2017-10-26 23:00
substratum is ore dict as stickiron and ironrod
the axle from crossroads is just stickiron.
which is odd since you can make machine structures with subtratum iron rod

**Comment by Thutmose** [comment] 2017-10-26 23:01
Odd it should work then, not sure why it doesn't, that part is definitely a separate bug from #881

**Comment by dmodoomsirius** [comment] 2019-03-03 23:43
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Closed by dmodoomsirius** 2019-03-03 23:43 UTC
