### ISSUE TITLE
[BUG] Something Wrong with doWeatherStuff

### ISSUE THREAD

**Issue by xlea99** [zmaster587/AdvancedRocketry#1690] opened 2019-09-04 22:53 UTC
## Version of Advanced Rocketry
Varying results on different versions, which I've tested at length. These are all with just vanilla and Advanced Rocketry installed, nothing else (except Avaritia so I can fly fast). I tested this on a generic Advanced Rocketry planet that was generated by the game, no planetDefs was ever specified. Each time I switched versions, I generated a new world as well. LibVulpes version was not changed from build -62. Here's what I found:

v139 and below: Never crashes, weather works perfectly fine on all planets capable of weather.

v149: Simply crashes the game when weather toggles, 100% of the time. Crash: https://pastebin.com/PQfLwk97

v150-179: This is where the game stops crashing. Instead, weather now simply doesn't work. Whenever the weather event triggers, it lasts for maybe a second (just long enough to a see couple rain drops or snowflakes) and then immediately stops again.

## Have you verified this is an issue in the latest unstable build
Yes.

## Version of LibVulpes
LibVulpes 0.4.1-62

## Version of Minecraft
1.12.2

## Does this occur without other mods installed
Yes, though the bug gets worse with other mods installed, specifically mods like Just Enough Dimensions, Dimensional Control, and Topography. 

## Description of the problem
To reproduce this problem, just make a fresh pack with just AR v150-179, go to a planet, and either toggle downfall or wait for weather to trigger. You can observe the weather briefly start, then immediately stop.

This problem gets much worse however with a mod that installs dimensions installed. Another thread about this was maybe 20 days ago, right here: https://github.com/zmaster587/AdvancedRocketry/issues/1670

Here's a crash report from my main modpack I've been working on. I keep getting this same error: https://pastebin.com/p8BZBiyw
It's always at problem at WorldProviderPlanet.doWeatherStuff and at WorldProviderPlanet.updateWeather.

This problem doesn't exist on or before version 139. It first becomes aparent in v149. Even with Dimensional Control installed, v139 will never crash, the weather will always work, etc.

I hope this is enough information to help solve the issue! Let me know if you need me to test anything else. Thanks for your time!

**Comment by MrEyeballs29** [comment] 2019-09-05 00:37
You know the spectator mode right. It goes fast too.

**Comment by zmaster587** [comment] 2019-09-05 02:29
It's looking like those mods replace worldInfo, that'd cause problems because AR expects the vanilla minecraft worldinfo to be there

**Comment by zmaster587** [comment] 2019-09-05 02:43
[AdvancedRocketry-1.12.2-1.6.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/3577228/AdvancedRocketry-1.12.2-1.6.0-universal.jar.zip)

Can you give this one a try?

**Comment by xlea99** [comment] 2019-09-05 07:59
This seems to have completely solved the crashes!! Been running it for about 5 hours, haven't crashed once. Thanks a bunch for the speedy reply, this is great!!

I also tested weather on a vanilla pack with the version you gave me, but it seems like weather is still not quite working correctly on AR planets. No crashes, it just auto-disables weather right when it triggers.

**Comment by zmaster587** [comment] 2019-09-10 07:15
@xlea99 Was this on a planet with low atmosphere that it was disabling weather?

**Comment by xlea99** [comment] 2019-09-22 22:02
@zmaster587 Sorry, didn't see that comment! No, I've tried testing it on all sorts of different planets, including 100 and 200 atmosphere planets. In any biome that allows rain/snow, it'll turn on briefly before turning off. I just verified the problem still exists in version 183.

**Comment by zmaster587** [comment] 2019-09-29 06:14
@xlea99 does this issue also occur with just AR and libvulpes and no other mods?

**Comment by SanAndreasP** [comment] 2020-01-08 21:16
So I have the same issue with the weather stopping to work after a second when toggling.

**LibVulpes**: 1.12.2-0.4.2-69
**Advanced Rocketry**: 1.12.2-1.6.0-194

**How to reproduce**:
You'll need some form of chunk loader to keep the space station dimension loaded when returning to the overworld from it. Weirding Gadgets works for me.

1. Create a new world with cheats enabled. Verify that rain works by entering the command
```/weather rain```
2. Build a space station, a rocket and fly up to the station.
3. Place a chunk loader somewhere on the space station
4. Return to the overworld with the rocket
5. Once landed, re-enter the ```/weather rain``` command and see how rain cannot be toggled on anymore

This is an issue for me since I have solar panels build on my station and want to use them for power generation.

**Closed** 2020-04-08 00:04 UTC
Labels: Unconfirmed Bug, no-issue-activity
