### ISSUE TITLE
NullPointerException at client on server join

### ISSUE THREAD

**Issue by ethanbrews** [zmaster587/AdvancedRocketry#760] opened 2017-06-29 20:51 UTC
A NullPointerException occurs client side when attempting to join the server (The client shows a fatal error occurred and will not join the server). It happens to all clients attempting to join the server, it only started when the server unexpectedly shut down while another player was building at a space station however the error persists after the dimension has been deleted.

```
There was a critical exception handling a packet on channel libVulpes
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:407)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:273)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at zmaster587.advancedRocketry.dimension.DimensionProperties.setStar(DimensionProperties.java:342)
	at zmaster587.advancedRocketry.dimension.DimensionProperties.readFromNBT(DimensionProperties.java:1190)
	at zmaster587.advancedRocketry.network.PacketDimInfo.readClient(PacketDimInfo.java:104)
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:210)
	at zmaster587.libVulpes.network.PacketHandler$Codec.decodeInto(PacketHandler.java:192)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:103)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:40)
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 40 more
```

**Comment by dmodoomsirius** [comment] 2017-11-02 21:50
What version of Minecraft? what version of LibVulpes and Advanced Rocketry?

**Comment by yokujin** [comment] 2017-11-07 09:19
Recently happened to me. Cannot connect to server which was stopped unexpectedly.
Minecraft 1.12.2
Advanced Rocketry 1.2.5a
LibVulpes 0.2.6-universal

**Comment by wil-langford** [comment] 2017-11-14 05:05
I'm getting the same issue:
    `AdvancedRocketry-1.12.2-1.2.5a.jar`
    `LibVulpes-1.12.2-0.2.6-universal.jar`

**Comment by bbf** [comment] 2017-11-14 05:10
I'm having the same issue, and I was only able to fix by disabling the mod. As soon as re-enable it comes back.
AdvancedRocketry-1.12.2-1.2.5a
LibVulpes-1.12.2-0.2.6-universal

My guess is that, in DimensionProperties.java:1190:
this.setStar(DimensionManager.getInstance().getStar(nbt.getInteger("starId")));
That nbt.getInteger() is returning an invalid id (or 0), and getStar is actually returning null.

**Comment by dmodoomsirius** [comment] 2017-11-14 05:27
We just released a new version on curseforge. https://minecraft.curseforge.com/projects/advanced-rocketry  I will be releasing a new version of LibVulpes once i finalize the scripts.

**Comment by zmaster587** [comment] 2017-11-14 05:27
Looks like #941

**Comment by zmaster587** [comment] 2017-11-14 05:28
could I get a copy of the advRocketry/temp.dat file?

**Comment by bbf** [comment] 2017-11-14 08:20
This includes everything under world/advRocketry in case you need anything else. No one has even come close to building a rocket for now.
[advRocketry.zip](https://github.com/zmaster587/AdvancedRocketry/files/1469992/advRocketry.zip)

**Comment by bbf** [comment] 2017-11-15 02:08
I browsed through my backups, and found the 2 saves that are before and after the file corruption. Although, even with that to narrow down when it happened, I couldn't find anything in the logs about any possible issue. Do you need anything else that could help to identify the issue?

I can possibly try to do a partial restore on the advRocketry folder, and see if it happens again.

**Comment by zmaster587** [comment] 2017-11-15 05:12
Very odd indeed, the files you sent contain no planet or star data whatsoever.  Did the server crash not long before this occured?  Can you see if it can be replicated from a known good copy of the data?

**Comment by bbf** [comment] 2017-11-15 18:19
The server hadn't crashed, the corruption happened while the server was online. I was able to join the server, and some time after, while I was still connected, a client could not connect. I disconnected and couldn't reconnect, reproducing the same issue.

I recovered the previous advRocketry folder, and so far the issue hasn't happened again.

**Comment by zmaster587** [comment] 2017-11-24 03:08
Alright, if it does, before shutting down the server, can you test having a client that's not having a problem close MC all the way and then attempt to reconnect.  Also run "/advRocketry star list" on the server and report the results.   And get the fml server log from the time the server started to the time the issues began occuring (or the whole thing).

**Comment by zmaster587** [comment] 2018-11-11 18:43
I'm not quite sure what's going on with that. I have no problem loading into the world with the latest release of AR on curse (112), and mcjtylib-1.12-3.0.6, rftools-1.12-7.56, and rftoolsdim-1.12-5.62, forge 1.12.2-14.23.4.2760 with a new world.

After the packet fix (which does not affect single player), i can also load in just fine on server worlds.
Depending on the order in which you installed the mods and loaded the world.  It's possible that one of AR's dimensions conflicts with one of RFtoolsdim.  I believe that can happen if you load a world with RFToolsDim, then add advanced rocketry later on.  Due to mod loading order issues, there's not too much I can do to fix this automatically.  But if this is the issue then you can fix it manually by changing the dimensions used in saves/<world name>/advRocketry/planetDefs.xml.
I cannot tell for sure if this is the issue or not since the snippit you provided is incomplete and dim conflicts would print way earlier.

So going forward, I'd advise checking for dim conflicts and changing the AR config to use dimensions that RFtools does not and make sure that's not an issue.  If that doesn't work, I may need a copy of the world for futher testing since I can't seem to get this to happen normally.

**Comment by Garagoth** [comment] 2018-11-11 23:11
RFTools Dimensions were added after AR.
What is worse, I cannot reproduce it on clean fresh install (just AR + RFTools Dimensions + dependencies), but it still crashes on old save with all the mods I have (and stops crashing without AR). So might be that something else is affecting this issue (and it is completely unrelated to setStar() issue here by the way).
Even worse - it was all working fine just 2 days ago! I am still trying to reproduce it with minimal steps required and a bit of guaranteed repetition...

Regarding the fix - I was asking for a fix for setStar() NPE, it is not on Curse and I cannot seem to locate any other AR builds (like jenkins/travis/...). Luckily my server is not affected with dimensions issue, only with clients failing to join it due to AR setStar() NPE issue...

**Comment by Garagoth** [comment] 2018-11-12 08:39
With ver 113 still same issue:
https://pastebin.com/aDimvsaY

**Comment by KaneHart** [comment] 2018-12-16 16:10
More Added Info:
If you use something like a in game Auth system to MC servers to get a new Token it will happen again without resetting the client. So it seems either new token or new id causes it each time. So If I flip accounts back / forth over and over you have to login to the server twice once with the error.

Making running server a tad hard lol, as some people don't give 2nd chance and assume it's broken. 

Thanks.

**Comment by takarabako** [comment] 2018-12-16 16:41
It seems some fix [in the sponge_login_fix branch](https://github.com/zmaster587/AdvancedRocketry/commit/2159fac300281c49ae33e15afd731df2b49d0b36) needs to be merged. The event part is now not needed though.

**Comment by zmaster587** [comment] 2018-12-16 23:07
I can undo the event bit and merge it later this evening

**Comment by zmaster587** [comment] 2018-12-17 05:45
@KaneHart I do not use any kind of auth system, it appears to be caused by packet reordering.  (planet packet is recieved and processed then star packet is recieved and processed) so the second time joining, the stars have been added.  I thought I fixed this issue at some point, let me double check.  Maybe it was in a different branch

**Comment by zmaster587** [comment] 2018-12-17 05:46
@KaneHart It's in 2159fac300281c49ae33e15afd731df2b49d0b36, I thought I made it into main, I apologise for the inconvience this caused.

**Closed** 2018-12-17 05:49 UTC
Labels: Needs Info, Unconfirmed Bug

**Comment by KaneHart** [comment] 2018-12-17 17:24
Thanks so much! Will have it added to 1.46 for Enigmatic 2 Expert once it's on curse!
