### ISSUE TITLE
Machines are eating items

### ISSUE THREAD

**Issue by Prometheus0000** [zmaster587/AdvancedRocketry#1359] opened 2018-07-20 16:49 UTC
## Version of Advanced Rocketry
AdvancedRocketry-1.12.2-1.4.0-91-universal
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
LibVulpes-1.12.2-0.2.8-34-universal
## Version of Minecraft
1.12.2

## Description of the problem
When you put multiple items into a machine such as the Lathe or Crystallizer, they consume the whole stack, but only produce one result, IE: 10 Steel Ingots becomes 2 Steel Rods when it should return 20. Putting in multiple types of ingots in the Lathe also results in all but one being consumed. I only tested these two machines, but it may be all the multiblock structures that take items. I tried putting the items in myself to see if it was automation related, but it still ate them. May be related to code changes in #1331?

**Comment by zmaster587** [comment] 2018-07-20 17:04
The only change made for #1331 was to mark the inventory as updated with machines in the same way inserting an item manually has been doing.  (Calling the inventory updated function in the main machine block once for every modification done via automation).  The reason this needed to be updated at all is because many machine's no longer use the IInventory interface and use a capability instead in 1.12.

Can you delete the recipe xml configuration files  (or back them up) before launching the game so they are regenerated new and see if the issue persists?

**Comment by Prometheus0000** [comment] 2018-07-20 17:15
I tried moving the Lathe.xml file, but it regenerated the same, and didn't fix the problem in-game. I'm using FTB continuum 1.4.1 (I updated AR+LV and IE though), does it work properly with just AR?

**Comment by dmodoomsirius** [comment] 2018-07-20 22:11
They may have modified recipes using craft tweaker. I’ll look at that aspect when I have the moment.

**Comment by Prometheus0000** [comment] 2018-07-20 22:13
As I mentioned, I tested it out as well on a new profile with basically just AR to check if it was that.

**Comment by zmaster587** [comment] 2018-07-24 00:07
I can confirm the issue exists without modification to the xml files

**Comment by zmaster587** [comment] 2018-07-24 00:16
It appears to be caused by the modification of the hatch "markdirty" function.  So your hunch that it was a result of #1331 being the culprit was spot on.

**Comment by zmaster587** [comment] 2018-07-24 00:43
Both issues should be fixed for next update of LibVulpes and AdvancedRocketry, you may need to either manually edit or regenerate the rolling machine XML file after the update.

**Closed by zmaster587** 2018-07-24 00:43 UTC
Labels: High Priority, bug
