### ISSUE TITLE
Crash to Desktop with Thermal Expansion + JEI:

### ISSUE THREAD

**Issue by talonos2** [zmaster587/AdvancedRocketry#805] opened 2017-08-05 01:40 UTC
Something about BlockPressurizedFluidTank is causing JEI to throw an exception.

* Make a modpack consisting solely of 
  * AdvancedRocketry (Tested with 1.11.2-1.2.2)
  * LibVulpes (Tested with 1.11.2-0.2.5)
  * CodeChickenLib (Tested with 1.11.2-3.0.0.287)
  * NotEnoughItems (1.11.2-2.3.0.227)
  * jei (Tested with 1.11.2-4.5.0.291)
* Open a new game and open your inventory.
* Navigate To the Advanced Rocketry Section.
* In the sport between the Unmanned Vehicle Assembler and the Gas Intake, there is a blank spot where a fluid tank should be:
![Missing Block](http://i.imgur.com/fPCgY8c.png)
* In the console, you will see that NEI has [thrown an error](https://pastebin.com/raw/TBPpAVnw) trying to display the block. ([Link](https://pastebin.com/raw/TBPpAVnw))
* If it helps, [this](https://github.com/mezz/JustEnoughItems/blob/a08d5a0b3e5491408bfd13751b7f93eedddaf8fd/src/main/java/mezz/jei/render/GuiIngredientFastList.java#L90) is the line in JEI that throws the error.

I believe this same issue is causing a crash to desktop when you add Thermal Expansion:

* To the above modpack, add
  * CoFHCore (Tested with 1.11.2-4.2.7.15)
  * Thermal Foundation (Tested with 1.11.2-2.2.5.16)
  * Thermal Expansion (Tested with 1.11.2-5.2.6.22)
* Open a new game. Enter your inventory.
* Try to search for the uses of water. (Hover your the water icon and press "U")
* Select the tab for the fluid transposer.
* Navigate to page 2.
* You will crash to desktop and get the following error: ([Link](https://pastebin.com/raw/nmCewjnM))
* I *suspect* this is because JEI tries to pull up the Liquid transposer recipes for water, one of which is to fill the buggy tanks. It tries to render the buggy tank, and is unable to, causing a crash.

**Comment by KelCo** [comment] 2017-08-06 01:12
Can confirm, I have the same issues with thermal expansion.

**Comment by zmaster587** [comment] 2017-08-06 01:32
I think this is a dupe of #735?

**Comment by talonos2** [comment] 2017-08-06 03:17
Quite Likely. Looking forward to next version, then! (The one where #721 is fixed)

**Comment by dmodoomsirius** [comment] 2019-03-03 23:31
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Closed by dmodoomsirius** 2019-03-03 23:31 UTC
