### ISSUE TITLE
[1.12.2] AR crafting recipes no longer oredict rods

### ISSUE THREAD

**Issue by Gamertech** [zmaster587/AdvancedRocketry#1558] opened 2019-04-07 05:28 UTC
## Version of Advanced Rocketry
1.5.0-137
## Have you verified this is an issue in the latest unstable build
Y
## Version of LibVulpes
0.4.0-54
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)
N/A

## Description of the problem
LibVulpes rods have oredict set (eg. rodIron) but Advanced Rocketry recipes requiring the rods are hardcoded to only use LibVulpes rods instead of being oredicted to any compatible rod.

The recipes still use oredict for plates, just not rods.

Ideally, AR recipes should be oredicted so they're compatible with rods from other mods.

**Comment by zmaster587** [comment] 2019-04-07 19:00
Would you be able to get me the name of the mod you're having issues with and a particular recipe in AR you're having issues with?  Advanced rocketry does use the ore dict for its recipies, but for the rods, it uses the "stickMETAL" naming scheme like immersive engineering.  Before changing over to JSON, both the "stickMETAL" and "rodMETAL" naming schemes were used.

**Comment by Gamertech** [comment] 2019-04-07 23:29
I've mirrored stickX and rodX to each other using CT, eg:

`<ore:rodIron>.addAll(<ore:stickIron>);
<ore:stickIron>.mirror(<ore:rodIron>);`

The mods that provide their own rods all use rodX. LightningCraft, Fun Ores and Silent Gems.

The affected AR recipes are all of them that use either Iron, Copper or Steel rods in their default recipes. So structure tower, saw blades, rocket monitoring etc.

I've removed all metal mod variants from the pack so machines only produce and require a single mod's version for each metal, so only 1 type of ingot/plate/rod etc for consistency.

I think it would've been the change removing rodX that did it, as previously I mirrored the rod oredict as before, then removed extra rods from each oredict, so recipes auto-defaulted to a single rod type. Now, even after re-adding all rods to oredict, the recipes would only accept the LV rods.

If you want to see it in the pack itself, https://minecraft.curseforge.com/projects/chaotic-progression
In 1.3.2 released yesterday, I replaced all the recipes of the affected crafts with CT, so check a previous version or delete the rocketry script.

Cheers for looking into this.

**Comment by zmaster587** [comment] 2019-04-10 00:47
the next build should have support for rods as part of the ore dict again out of the box.  I'd really appriciate feedback on if it's working for you or not.  If it is, just closing the issue is feedback enough.

**Comment by Gamertech** [comment] 2019-04-10 01:58
Will do. Thanks mate

**Comment by Gamertech** [comment] 2019-04-11 02:58
Working as intended for most recipes, they show as duplicate recipes in JEI with 1 showing LV rods (which can't be crafted), the other showing the rods I've set, but not really an issue.

Some recs still only show the LV rods though:
Small Battery
Machine Structure block
Motors

**Comment by zmaster587** [comment] 2019-07-13 21:31
should be fixed after cleaning up the recipe config XMLs

**Closed** 2019-07-13 21:31 UTC
Labels: Mod Interaction, bug
