### ISSUE TITLE
Issue with teleporting and getting stuck in ground

### ISSUE THREAD

**Issue by JoeSGT** [zmaster587/AdvancedRocketry#995] opened 2017-12-19 08:29 UTC
Minecraft Version:
- 1.12.2
Forge Version:
- 
Advanced Rocketry Version:
- 1.12.2-1.2.5a-13
LibVulpes Version:
- 1.12.2-0.2.6-8

**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report:
----------
Explain issue in detail:
the issue is when having advanced Rocketry mod installed and you teleport either to player or any form of teleporting using vanilla command you can get stuck ingame underground
more in detail about this issue can be found here
i did a lot of testing with this and made sure of this mod was the cause
https://github.com/NucleusPowered/Nucleus/issues/1027

**Comment by zmaster587** [comment] 2017-12-21 04:10
Can you give an exact command you're using with exact results and what you expect differently?

I've tried standing at the position 4, 66, 64 (the player is standing on solid ground) and run the command "/tp 4 66 64" and nothing out of the ordinary is happening to me, I just get dumped on top of the block.  Same thing if I stand a distance away.  This being with Advanced Rocketry and libvulpes installed.

**Comment by JoeSGT** [comment] 2017-12-21 07:44
here what i did 
have loaded up a fresh Forge server with  Advanced Rocketry and libvulpes installed
and have 2 client's with me and my alt
then i have my alt just stand on the ground in survival
on my main account i then use `/tp <random cords>` away from my alts
then you tp to my alts then i get stuck in ground
sometimes you need to restart the server after you have teleport to randoms cords because sometimes you need to unload the chunk
but yea this is how did it
let me know if you can reproduce it or if not ill explain a bit more as best as i can

**Comment by zmaster587** [comment] 2017-12-22 03:02
So you have two players, you go somewhere else with your main account, but when you TP to one of the alternate players you get stuck in the ground?

**Comment by JoeSGT** [comment] 2017-12-22 03:12
yes

**Comment by zmaster587** [comment] 2017-12-22 03:31
Alright, I was able to replicate the issue.  Though the only thing I can think of is the gravity, though it still occurs even with gravity disabled.

**Comment by zmaster587** [comment] 2017-12-22 03:47
Confirmed, it is related to the gravity handler.

**Comment by JoeSGT** [comment] 2017-12-22 05:17
a thanks for fixing the issue i was wondering when will there be a stable release so i can have this stable update with this fix cause it's super annoying teleporting and getting stuck

**Comment by zmaster587** [comment] 2017-12-22 06:10
It should show up on curse in the next 24 hours.  Also note that there are still issues with high gravity planets, though I don't think it'd be able to fix that tonight.

**Comment by JoeSGT** [comment] 2017-12-22 06:17
ah okay and last question in your personal opinion do you think it's stable on the latest curse site
because i was scared not to update because there was a clear warning that it may break worlds

**Comment by zmaster587** [comment] 2018-01-04 02:49
As of right now the unstable builds have only been bugfixes, so they're actually more stable than the stable builds right now.  The reason it's marked as unstable is because I cannot garuntee things other than bugfixes will get in there here and there

**Closed by zmaster587** 2018-01-04 02:49 UTC
Labels: bug, MC 1.12.2
