### ISSUE TITLE
Game crash for advanced rocketry

### ISSUE THREAD

**Issue by Brianng0924** [zmaster587/AdvancedRocketry#2131] opened 2021-05-29 08:05 UTC
## Version of Advanced Rocketry
[2.0.0-12-universal]
## Have you verified this is an issue 
Y,N, N/A
## Version of LibVulpes
[1.0.2-25-universal]
## Version of Minecraft 
[1.16.5 forge+optifine(Tlauncher)]
## Crash report or log (if applicable)
http://pastebin.com is a good place to put them
crash reports that are put in the issue itself are
hard to read
[No crash report available.]

## Description of the problem
[Game crash while opening guidence computer that installed on the rocket,there is no reason for crashing the game. I tried atleast 4 time and trying to reducing the mods that install ,but it is not working. Hope my problem is letting you understand.]

**Comment by voidsong-dragonfly** [comment] 2021-05-29 15:39
Duplicate of #2132

**Closed as completed by voidsong-dragonfly** 2021-05-29 15:39 UTC
