### ISSUE TITLE
A fatal error has occurred, this connection is terminated.

### ISSUE THREAD

**Issue by Explosivee** [zmaster587/AdvancedRocketry#1067] opened 2018-01-14 17:25 UTC
Minecraft Version:1.12
-
Forge Version: 14.23.1.2573
-
Advanced Rocketry Version: AdvancedRocketry-1.12.2-1.2.6-42
-
LibVulpes Version: LibVulpes-1.12.2-0.2.7-24-universal
-
**is this the latest curseforge build?**

#Please Pastebin crash
---------------------
Crash Report: http://paste.feed-the-beast.com/view/305161d5
----------
Explain issue in detail: I own a FTB Revelation server and 90% of my users and myself cant login into server becasue of AdvRocketry they are getting "FatalError" the only fix i found is "join random FTB Revelation v1.2 server then disconnect and back to my server again.

**Comment by zmaster587** [comment] 2018-01-21 04:12
duplicate of #1004. if you find a way to reliably go from a working instance to an unworking instance, please post there.  Or if you're looking for more info on the issue in general

**Closed by zmaster587** 2018-01-21 04:12 UTC
