### ISSUE TITLE
Terraformer

### ISSUE THREAD

**Issue by forestbat** [zmaster587/AdvancedRocketry#653] opened 2017-05-25 05:17 UTC
I put nitrogen in 3 hatches and oxygen in 1 hatch，and the terraformer doesn‘t work。
![2017-05-25_13 06 08](https://cloud.githubusercontent.com/assets/23413915/26436908/747f5b6c-414c-11e7-8be3-58203b6f5af4.png)
![2017-05-25_13 05 03](https://cloud.githubusercontent.com/assets/23413915/26436909/74807d44-414c-11e7-91ca-b37cfa2f28c4.png)
![2017-05-25_13 05 17](https://cloud.githubusercontent.com/assets/23413915/26436910/748073a8-414c-11e7-8337-58bf6590ceae.png)

**Comment by zmaster587** [comment] 2017-05-26 18:30
It's designed to be two O2 hatches and two N2 hatches, but that's also known to not work.  Temporary workaround is to just disable the terraformer requiring fluid in the config.  Will hopefully have it fixed in the near future

**Comment by zmaster587** [comment] 2017-05-31 00:53
Upon further testing it appear to work fine when fluids are piped in fast enough.  Are both allowTerraforming and EnableTerraforming set to true in the config?

**Comment by forestbat** [comment] 2017-05-31 06:53
AllowTerraforming was set to false and I changed it。Now it can work。
But when I leave GUI of terraformer，it closed—I must decrease the atmosphere pressure with clicking again and again。What happened？

**Comment by zmaster587** [comment] 2017-05-31 18:36
What do you mean it closed when you leave the GUI?  Are you saying the terraformer stopped working?  Also is this multiplayer or single player?

**Comment by zmaster587** [comment] 2017-05-31 20:28
Hold on, I just noticed something about the 1st image, a connected biome changer remote appears to be missing.

**Comment by zmaster587** [comment] 2017-06-01 17:19
The terraformer requires a biome changing satellite to function.  The reason it stops when you close the UI I suspect (and what i found in testing) is that the server (or integrated server in single player) checks for the biome satellite remote in the UI slot and doesn't find it and disables the machine, but the change in status does not register on the clients UI.  Reopening the machine syncs the UI with the server/integrated server.
I've put together a new build with an overhauled UI that actually tells the player what's wrong if you want to give it a whirl, but I'll need to know what version of the mod and MC you're using so I can give you the correct link.

**Comment by forestbat** [comment] 2017-06-02 04:54
MC 1.10 and AR 1.2.0b，I will follow the newest version in later issues。
And what is“0.01% atm”？If I want to change 0.25 atm，will I need 2500*720=1.8e6 bukkit of oxygen？

**Comment by zmaster587** [comment] 2017-06-02 07:06
It should read 1% on the wiki, I think when I wrote that I had it in my head that the terraformer would display atmosphere pressure in atm where Earth would be 1, not 100%.  I confirmed this in the in the code here https://github.com/zmaster587/AdvancedRocketry/blob/RoundPlanets1_10/src/main/java/zmaster587/advancedRocketry/tile/multiblock/TileAtmosphereTerraformer.java#L480

So I'll make sure to update the wiki, therefore it should use 25*720 = 18,000 buckets to bring the atm from 0 to 25.  Also if that's too much there's a config option to modify the amount of fluid required per tick.  I'll get a build up on the jenkins with the updated UI and link it in a few minutes.

**Comment by forestbat** [comment] 2017-06-02 10:02
OK I will try to launch a biome changer satellite later，if the problem is solved，I'll close the issue。

**Comment by forestbat** [comment] 2017-06-02 16:07
Yes it's all right。

**Comment by forestbat** [comment] 2017-06-03 07:30
How to get nitrogen？

**Comment by zmaster587** [comment] 2017-06-05 06:02
Gas mining missions http://arwiki.dmodoomsirius.me/guides/Missions.php is currently the only way to get nitrogen and can also supply oxygen.
Basically you have to launch a autonomous drone from a station orbiting a gas giant.

**Comment by forestbat** [comment] 2017-06-06 05:51
I don't understand wiki very well.If I build a autonomous drone to gain gas,what blocks do I need to build it
?

**Comment by zmaster587** [comment] 2017-06-06 17:07
I'll make sure to update that in the wiki when I get a chance.
You need some number of intakes, fluid tanks, fuel tanks, an rocket engines.  More intakes reduces mission time, and more fluid storage increases the harvest

**Closed** 2018-02-25 12:28 UTC
Labels: Unconfirmed Bug
