### ISSUE TITLE
Mysterius crash once in a while not reprodible manually....Crash reports point to AR see attachment..

### ISSUE THREAD

**Issue by jonabrv1965** [zmaster587/AdvancedRocketry#472] opened 2017-03-27 17:40 UTC
Hi Zmaster, I' having the crash detailed below. It happens randomly in any dimension (overworld, nether, moon, etc.) as a matter of fact had happened while standing still doing nothing... seems some kind of programmed task. once happened  I start MC and the the world and everything works just fine (until the next crash)....

I'm attaching the last four crash reports if that help to solve this...

[crash-2017-03-27_12.29.23-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/873291/crash-2017-03-27_12.29.23-server.txt)

[crash-2017-03-27_00.40.03-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/873292/crash-2017-03-27_00.40.03-server.txt)

[crash-2017-03-26_23.08.57-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/873294/crash-2017-03-26_23.08.57-server.txt)

[crash-2017-03-26_20.39.26-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/873295/crash-2017-03-26_20.39.26-server.txt)

**Comment by jonabrv1965** [comment] 2017-03-27 20:17
Since my past posting I had three crashes more (is worsening) here  my latest crash report and the correspondent FML log...

[crash-2017-03-27_14.53.53-server.txt](https://github.com/zmaster587/AdvancedRocketry/files/873651/crash-2017-03-27_14.53.53-server.txt)


[fml-client-latest.log.txt](https://github.com/zmaster587/AdvancedRocketry/files/873656/fml-client-latest.log.txt)

The only change I made to my installation was that I installed Malisis Doors mod. Before that all worked fine. After it, it works fine for several game hours (I installed Malisis at march 25 7pm, and the first crash happened at march 26 9;34am) at least 4 hours without problems. Now is crashing every hour.

The other thing new is that I started to gather Oxygen from the gas giant (I already got lots of Nitrogen without problems), as a matter of fact I lost one gas ship (never come back) so I create a new one and launch it.

I'm uninstalling malisis door to start a debugging process....I'll let you know...

**Comment by zmaster587** [comment] 2017-03-27 21:12
There is a known bug where a gas/asteroids mining mission will produce this crash upon completion.  It's been fixed on git but has not yet been released on curse.  So I suspect that's probably the cause

**Comment by jonabrv1965** [comment] 2017-03-27 21:30
Hi Zmater, thank you for the promptly answer!. I just test a asteroid mining mission and yes, in the exact moment it completes the gathering (I was seeing the rocket station display in that moment) the game crashed...

The weird part is that I made at least a dozen of asteroid missions without a glitch... funny thing, maybe this started with the gas missions and affects all the gathering activities... I'll stop my mining missions until you release the next version.

Thanks again and best regards!

PS (By the way the latest crash happened without the malisis mod, so...)

**Comment by zmaster587** [comment] 2017-04-04 02:47
Yesterday's build should contain the patch, if you could get back to me on if it's fixed or not, i'd appriciate it

**Comment by jonabrv1965** [comment] 2017-04-04 15:50
Hi, tested and fixed now. Only one thing. I got my miner rocket
"cloned" three times and appeared one above the other (4 rockets
stacked, funny)... I guess this were the three failed missions I sent
before the fix...

I have not tested the gas collection yet... I'll let you know...

**Comment by jonabrv1965** [comment] 2017-04-04 17:11
Oops... today open MC load my world and found 6 rockets stacked, see image :
![2017-04-04_12 09 24](https://cloud.githubusercontent.com/assets/13445986/24669350/b05f7896-192f-11e7-8749-a5ca39f9393e.png)

**Comment by zmaster587** [comment] 2017-04-04 19:00
Likely related to #493, working on a fix for that right now

**Comment by zmaster587** [comment] 2017-04-08 00:15
The duplication should now be fixed in the most recent builds

**Closed by zmaster587** 2017-04-08 00:15 UTC
Labels: bug, Unconfirmed Bug
