### ISSUE TITLE
BlockPos - Spam 

### ISSUE THREAD

**Issue by Keaton1188** [zmaster587/AdvancedRocketry#1124] opened 2018-02-02 17:54 UTC
Minecraft Version:
- 1.12.2
Forge Version: - 14.23.1.2587

Advanced Rocketry Version: 
- AdvancedRocketry-1.12.2-1.2.6-42.jar

LibVulpes Version: 
- LibVulpes-1.12.2-0.2.7-24-universal.jar
**is this the latest curseforge build?**

We are getting a lot of spam on our Revelations server:
![untitled](https://user-images.githubusercontent.com/24898745/35747412-18ca4bca-0842-11e8-8012-5e88113eb5f8.png)

**Comment by zmaster587** [comment] 2018-02-04 23:48
duplicate of #1023, fixed in build 43

**Closed by zmaster587** 2018-02-04 23:48 UTC
