### ISSUE TITLE
Holo-Projector Crash

### ISSUE THREAD

**Issue by Luckie21** [zmaster587/AdvancedRocketry#248] opened 2016-10-16 03:18 UTC
im experiencing a crash with the holo-projector. the steps that produce the crash are as followed.

1. Sneak right-click to open the gui of the holo projector 
2. Select any machine (doesnt matter which one for me). 
3. exit gui
4. right click the ground to project the multiblock machine 
5. Crash and then proceed to throw something across my room.

Here is my crash report!
[advanced_rocketry_crash_report.txt](https://github.com/zmaster587/AdvancedRocketry/files/531559/advanced_rocketry_crash_report.txt)

Here is my FML lastest log of when the crash happened!

[21:56:37] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at zmaster587.libVulpes.tile.multiblock.TilePlaceholder.getReplacedMeta(TilePlaceholder.java:34) ~[TilePlaceholder.class:unspecified]
	at zmaster587.libVulpes.block.BlockPhantom.getPickBlock(BlockPhantom.java:64) ~[BlockPhantom.class:unspecified]
	at mcjty.theoneprobe.rendering.OverlayRenderer.requestBlockInfo(OverlayRenderer.java:278) ~[OverlayRenderer.class:?]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:210) ~[OverlayRenderer.class:?]
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:112) ~[OverlayRenderer.class:?]
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:97) ~[ClientProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_315_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:694) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:171) ~[GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072) ~[bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by Luckie21** [comment] 2016-10-16 03:19
Edit: 

I tested this in a creative world and it does the same thing

**Comment by TheGuyRunningSouth** [comment] 2016-10-16 03:24
Looks like a duplicate of #218. @Zmaster587 will have to double check me,
but I think this should be fixed in the next release.

**Comment by Luckie21** [comment] 2016-10-16 03:34
Edit:
 Sorry forgot to include some important info

when i re enter the world the holo projector blocks arent there unlike #218

**Comment by zmaster587** [comment] 2016-10-16 03:56
The crash itself appears to be called from TESR rather than a UI overlay, the patch for #218 should cover this one too though.

**Closed by zmaster587** 2016-10-16 03:56 UTC

**Comment by Luckie21** [comment] 2016-10-16 04:12
Has that patch been released yet?

**Comment by zmaster587** [comment] 2016-10-16 04:12
No, but I plan to do so within the next hour or so.

**Comment by Luckie21** [comment] 2016-10-16 04:14
Awesome thanks. Ill be looking forward to it because ive been building my machines for youtube  and pictures. BTW awesome mod uve created I cant find another one that implentments rockets for 1.10.2

**Comment by zmaster587** [comment] 2016-10-16 04:19
No Problem, I've been kinda mystified where the NPEs with the holo projector is coming from, I've not actually been able to replicate this issue myself, and the only possible way I can even see it happening if there is somehow a delay between TE creation and the TE having it's data loaded, but that should all be done in one tick so..  Just adding null checks bascially and hoping nobody notices the block being air for a split second.  Better than crashing though

**Comment by Luckie21** [comment] 2016-10-16 04:25
Hey do support paetron or anything? im have a "little" spare cash and wont mind donating a little to u to keep u modding for us people who dont have that talent!

**Comment by zmaster587** [comment] 2016-10-16 04:33
No I don't have a paetron.  But I'll keep writing mods anyway because ironically it's how i can stay calm.

**Comment by Luckie21** [comment] 2016-10-16 04:34
Ok! Sweet!

**Comment by Luckie21** [comment] 2016-10-16 04:40
If u ever set one up just let me know ill be willing to donate! even if its for keeping a website  running

**Comment by Luckie21** [comment] 2016-10-16 04:42
just saw the release of the new beta release ill let u know it if fixed it.

**Comment by Luckie21** [comment] 2016-10-16 04:49
YIPPY! NO MORE CRASH! Thanks so much. BLAST OFF--- T-MINUS 10 SECONDS!!!
