### ISSUE TITLE
Crash on entering Station dimension (Sponge)

### ISSUE THREAD

**Issue by krisjenner** [zmaster587/AdvancedRocketry#1447] opened 2018-11-27 07:49 UTC
## Version of Advanced Rocketry
1.4.1-108
## Have you verified this is an issue in the latest unstable build
N
## Version of LibVulpes
1.12.2-0.2.8-39
## Version of Minecraft
1.12.2
## Crash report or log (if applicable)

[log](https://gist.github.com/krisjenner/e885c423ca71ba39e5c63c812a01cc9e)
[crashreport](https://gist.github.com/krisjenner/30b5e4e021f949779cfbadc67bbcbdea)

## Description of the problem
/advrocketry goto -2 == instacrash

**Comment by zmaster587** [comment] 2018-12-06 01:11
Duplicate of #1445

**Closed by zmaster587** 2018-12-06 01:11 UTC
Labels: duplicate
