### ISSUE TITLE
Game crashes when removing a chip from a Guidance Computer

### ISSUE THREAD

**Issue by duncanwebb** [zmaster587/AdvancedRocketry#687] opened 2017-06-06 14:25 UTC
Sometimes the game crashes when removing a planet id chip from a guidance computer. This intermittent and I have a number of crash logs it it help, I'll attach the last two.

[crash-2017-06-05_16.51.21-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1055297/crash-2017-06-05_16.51.21-client.txt)
[crash-2017-06-02_14.42.56-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/1055298/crash-2017-06-02_14.42.56-client.txt)

**Comment by zmaster587** [comment] 2017-06-06 17:01
Neither of these crash reports involve the guidance computer.

The first crash appears to be from the warp controller, however it's not possible for data to be null as the report indicates.  Two issues: that same variable is used when first opening the UI, and this crash definately occured after that.  Second, there's no place in the code where it is set to null, and it is initialized in the constructor.

The second report indicates that the world reference itself is null, which also should not be able to happen without external interaction, and does not occur in forge alone.

Because of these, I strongly suspect there is some kind of mod interaction going on.  Best I can say is try to find some reliable way of replicating the issues, or at least reliable enough so you can be reasonably sure it's broken or fixed then begin removing mods and testing again.

**Comment by zmaster587** [comment] 2017-06-07 01:36
I've had a few other reports of the first crash you linked, I've got that fixed now

**Comment by duncanwebb** [comment] 2017-06-07 08:41
Thanks, these type of crashes are very difficult to reproduce. I tend to swap the planet chip even when travelling between the earth and the moon, rather than set the destination. A crash may happen every once in 10 changes. I've updated my versions to the latest and will update this issue every time I get a crash. Thanks.

**Comment by zmaster587** [comment] 2017-06-07 15:37
It'd be much more organized and easier for me to have a different issue for each unique crash report.  Because then I can just look at it and know what yet needs to be fixed instead of potentially reading a whole comment chain.

But yeah, I understand these are hard to reproduce.  You're not the first with this issue, and nobody before to replicate it reliably either and I've never even encountered it myself.

**Comment by duncanwebb** [comment] 2017-06-07 18:54
No problem, will do

**Closed** 2017-06-07 21:00 UTC
Labels: Unconfirmed Bug

**Comment by duncanwebb** [comment] 2017-06-29 14:28
I removed a chip today and the game crashed. The memory usage was very high, the game has 10GB allocated and process explorer was reporting it was using 12.5GB. Could this be an out of memory condition? I reckon that after exploring for a while the memory usage goes up.
